[#174695208] Saves a cookie on web playground
pagopa/io-app pull request #2198
Opened 2020-09-15 13:04 UTC by CrisTofani

## Short description
This PR adds the feature to save a cookie from the web playground.

<img src="https://user-images.githubusercontent.com/3959405/93213830-a6799e80-f764-11ea-83ce-d6d7ad408e36.gif" height="550"/>

2020-09-16 10:02 UTC, Undermaken requested changes

2020-09-16 10:06 UTC, CrisTofani commented on ts/screens/profile/WebPlayground.tsx
> +              onPress={() => {
The reload with setReloading was a junky trial I did to make the webview reload cookies, but was useless and solved with the use of useWebKit param to true on set function

I'm going to clean the code in next PR

2020-09-16 10:19 UTC, CrisTofani commented on ts/screens/profile/WebPlayground.tsx
> +              onPress={() => {
6609603 for the changes

2020-09-18 08:56 UTC, Undermaken approved these changes

2020-09-18 08:56 UTC, merged