[#175741977] Fixes cut sticky header
pagopa/io-app pull request #2400
Opened 2020-11-18 10:13 UTC by CrisTofani

## Short description
This PR fixes the cut sticky header in wallet home screen

<img src="https://user-images.githubusercontent.com/3959405/99512366-a75bc600-2989-11eb-8d76-206ad5c7a6e2.gif" height="550"/>

2020-11-18 10:40 UTC, Undermaken requested changes
With the wallets shown on the left side, the header seems lefts some space on top
(iPhone 11 - 13.5)

<img src="https://user-images.githubusercontent.com/822471/99519949-c9a61180-2992-11eb-9eb9-c5556474b644.jpg" height="700"/>

2020-11-20 17:29 UTC, Undermaken commented
@CrisTofani is this PR ready?

2020-11-20 18:25 UTC, CrisTofani commented
> @CrisTofani is this PR ready?

@Undermaken I did the fix as we discussed with a midrange value, but was checking a more efficient one, anyway i guess the only way is a native module. 

I just pushed the fix.

2020-11-23 14:53 UTC, Undermaken approved these changes

2020-11-23 14:53 UTC, merged