[#175060536 new design delete profile]
pagopa/io-app pull request #2401
Opened 2020-11-18 10:57 UTC by debiff

## Short description
This PR handle the delete profile flow.

## List of changes proposed in this pull request

-  managed the profile deletion
-  added RadioButtonList core component
- managed the abort of the profile deletion

![deleteProfile](https://user-images.githubusercontent.com/11773070/99521607-ec392a00-2994-11eb-8ced-f5a2fd911c34.gif)

2020-11-19 09:05 UTC, Undermaken requested changes

2020-11-19 09:05 UTC, Undermaken commented on ts/screens/profile/RemoveAccountDetailsScreen.tsx
> +  const isLoading =
```suggestion
  const isLoading =
    pot.isLoading(userDataProcessing[UserDataProcessingChoiceEnum.DELETE]) ||
    pot.isUpdating(userDataProcessing[UserDataProcessingChoiceEnum.DELETE]);
```

2020-11-19 09:13 UTC, Undermaken requested changes

2020-11-19 09:13 UTC, Undermaken commented on ts/screens/profile/RemoveAccountDetailsScreen.tsx
> +          onRetry={() => true}
?

2020-11-19 17:52 UTC, debiff commented on ts/components/RemovedAcoountInfoOverlay.tsx
> +      {/* <View style={{ paddingVertical: 15, paddingRight: 24 }}> */}
@Undermaken This component is never used. We chosen to use the alert instead.
It's better if I remove it?

2020-11-20 13:54 UTC, debiff commented on ts/components/core/selection/RadioButtonList.tsx
> +export const RadioButtonList = <T,>(props: Props<T>) => {
I didn't get this.
Can you explain it please?

2020-11-20 17:16 UTC, Undermaken approved these changes

2020-11-20 17:17 UTC, merged