[#175780105] add missing action mixpanel
pagopa/io-app pull request #2413
Opened 2020-11-23 10:28 UTC by debiff

## Short description
This PR tracks the following actions in mixpanel

## List of changes proposed in this pull request
| action | tracked payload |
|:-------:|:----|
|`bpdAmountLoad.request`  | { **awardPeriodId**: id del periodo del bonus}|
|`bpdAmountLoad.success`  | - |
|`bpdAmountLoad.failure`  | { **reason** } |
|`bpdPeriodsLoad.request`  | - |
|`bpdPeriodsLoad.success`  | { **count** : numero di periodi ricevuti } |
|`bpdPeriodsLoad.failure` | { **reason** }  |
|`bpdSelectPeriod` | { **awardPeriodId**: id del periodo selezionato }  |
|`bpdPaymentMethodActivation.request` | { **hashPan**: hashpan del metodo di pagamento }  |
|`bpdPaymentMethodActivation.success` |  { **hashPan**: hashpan del metodo di pagamento, **activationStatus**: stato di attivazione, **activationDate**: (opzionale) data di attivazione del metodo di pagamento, **deactivationDate**: (opzionale) data di disattivazione del metodo di pagamento  }  |
|`bpdPaymentMethodActivation.failure` | { **hashPan**: hashpan del metodo di pagamento, **reason** }  |
|`bpdUpdatePaymentMethodActivation.request` | { **hashPan**: hashpan del metodo di pagamento, **value**: boolean(il nuovo valore che l'utente vuole cambiare }  |
|`bpdUpdatePaymentMethodActivation.success` |  { **hashPan**: hashpan del metodo di pagamento, **activationStatus**: stato di attivazione, **activationDate**: (opzionale) data di attivazione del metodo di pagamento, **deactivationDate**: (opzionale) data di disattivazione del metodo di pagamento  }  |
|`bpdUpdatePaymentMethodActivation.failure` |  { **hashPan**: hashpan del metodo di pagamento, **reason** }   |

2020-11-23 10:58 UTC, CrisTofani approved these changes

2020-11-23 14:38 UTC, Undermaken requested changes

2020-11-23 14:38 UTC, Undermaken commented on ts/features/bonus/bpd/analytics/index.ts
> +      return mp.track(action.type, { reason: action.payload });
```suggestion
      return mp.track(action.type, { awardPeriodId: action.payload });
```

2020-11-23 16:20 UTC, fabriziofff requested changes

2020-11-23 16:20 UTC, fabriziofff commented on ts/features/bonus/bpd/analytics/index.ts
> +      return mp.track(action.type);
```suggestion
    case getType(bpdAmountLoad.success):
      return mp.track(action.type, {
        awardPeriodId: action.payload.awardPeriodId
      });
```
My fault, I forgot this case!

2020-11-23 18:23 UTC, Undermaken approved these changes

2020-11-24 08:46 UTC, fabriziofff approved these changes

2020-11-24 08:48 UTC, merged