[#175857824] dispatched sessionExpired on getWallets failure
pagopa/io-app pull request #2481
Opened 2020-12-02 17:44 UTC by DavideValdo

## Short description
When the session is expired, the related screen should be shown

<img width="280" alt="session-expired-screen" src="https://user-images.githubusercontent.com/26572302/100910367-2d215a80-34ce-11eb-9732-7784e6675719.png">

## How to test

1. In the dev server, fake a 401 response from the `wallets/v2/wallets` API call
2. Just go to the payment methods tab or pull to refresh

2020-12-03 14:15 UTC, Undermaken requested changes

2020-12-03 14:15 UTC, Undermaken commented on ts/sagas/wallet/pagopaApis.ts
> +    yield put(sessionExpired());
In this way we consider a session invalid when an exception is raised.

Instead we have to consider a session invalid **only** when the response is right and the http status code is [401](https://httpstatuses.com/401) 
see https://github.com/pagopa/io-app/blob/8fe7cff334b89bf919fd9dd45843c37d78079ee3/ts/sagas/profile.ts#L65

2020-12-10 19:25 UTC, Undermaken approved these changes

2021-01-15 10:02 UTC, Undermaken approved these changes

2021-01-15 15:29 UTC, debiff approved these changes

2021-01-19 08:47 UTC, merged