[#176072451] missing actual screenshot attachment UX
pagopa/io-app pull request #2545
Opened 2020-12-09 18:53 UTC by DavideValdo

## Short description
A checkbox to express one's will to also attach a screenshot has been added to the "Write to the IO team" screen. 

## How to test
- Click the ? sign on almost any screen
- Scroll through the text and click "Write to the IO team"
- Scroll through the end and see the checkbox

<img width="427" alt="Schermata 2020-12-09 alle 19 51 02" src="https://user-images.githubusercontent.com/26572302/101673900-10e66600-3a58-11eb-9209-adfb9528524e.png">

2020-12-15 08:43 UTC, Undermaken requested changes

2020-12-15 08:43 UTC, Undermaken commented on ts/components/SendSupportRequestOptions.tsx
> +            sendScreenshot: sendScreenshot as boolean
```suggestion
            sendScreenshot
```

2020-12-15 08:43 UTC, Undermaken commented on ts/components/ContextualHelpModal.tsx
> +            initialScreenshotCheckboxValue={false}
```suggestion
```
For now it's better to keep the default behavior: don't ask about screenshot sharing.

2020-12-15 08:43 UTC, Undermaken commented on ts/components/SendSupportRequestOptions.tsx
> +  initialScreenshotCheckboxValue: boolean | undefined;
```suggestion
  initialScreenshotCheckboxValue?: boolean;
```
in this way you can avoid to define this property when you're using this component

2020-12-21 17:08 UTC, debiff requested changes

2020-12-21 17:08 UTC, debiff commented on ts/components/SendSupportRequestOptions.tsx
> +            <View style={{ flex: 1 }}>
it is better to use:
`<View style={IOStyles.flex}>`

2020-12-22 17:10 UTC, Undermaken approved these changes

2020-12-28 10:47 UTC, debiff approved these changes

2020-12-28 11:27 UTC, CrisTofani approved these changes

2020-12-28 14:18 UTC, merged