[#176167278] Show message when remove profile if some bonus is active
pagopa/io-app pull request #2597
Opened 2020-12-15 16:44 UTC by debiff

## Short description
This PR show an alert to inform the user that has some bonus active when choice to remove the profile.
If the user hasn't any active bonus the flow it's unchanged.

## List of changes proposed in this pull request
- Added alert if the user that are deleting the profile has at least one active bonus
-Request bonus information with a new saga if the user are deleting his profile and the bonus information aren't loaded yet. 

<img src="https://user-images.githubusercontent.com/11773070/102244628-d4ee4d80-3efc-11eb-9bd9-01eed21946d2.gif" width=300>

2020-12-16 09:00 UTC, Undermaken requested changes

2020-12-16 09:00 UTC, Undermaken commented on ts/screens/profile/RemoveAccountInfoScreen.tsx
> +  loadBonusAndProceed: () => dispatch(loadBonusBeforeRemoveAccount())
What happen if the API response with a delay? we press the button but nothing happens
To take it easy I suggest to remove the navigation from saga `handleLoadBonusBeforeRemoveAccount` and place it there.
So you at the same time

- ask for bonus data
- navigate to the next screen

If we can't load data the alert won't be shown. But I guess it is acceptable

2020-12-16 10:20 UTC, debiff commented on ts/sagas/startup.ts
> +  yield takeEvery(
Agree

2020-12-16 16:02 UTC, Undermaken requested changes

2020-12-16 16:02 UTC, Undermaken commented on ts/screens/profile/RemoveAccountDetailsScreen.tsx
> +  const handleSendMotivaiton = (
```suggestion
  const handleSendMotivation = (
```

2020-12-16 16:02 UTC, Undermaken commented on ts/store/actions/profile.ts
> +export const loadBonusBeforeRemoveAccount = createStandardAction(
Could you leave a comment describing why this action is needed?

2020-12-23 10:43 UTC, Undermaken approved these changes

2020-12-23 13:30 UTC, merged