[#176193672] Last update component
pagopa/io-app pull request #2617
Opened 2020-12-18 15:26 UTC by debiff

## Short description
This PR create a component that shows the last time the periods are loaded successfully and allows to reload the periods. 
If the periods data are not loaded yet only the "update" buttons is visible.
If the periods request fails, an error toast is shown. 

This component is added to the bpdDetail screen.

## List of changes proposed in this pull request
- Created the `lastUpdate` entry in the store
- Created the lastUpdate component
- Added the lastUpdate component to `BpdDetailScreen`

<img src="https://user-images.githubusercontent.com/11773070/102626186-c6937200-4146-11eb-8a26-9b196953bb38.gif" width=300> <img src="https://user-images.githubusercontent.com/11773070/102626219-ceebad00-4146-11eb-9aa8-7ba2da9de3bd.gif" width=300>

2020-12-22 15:56 UTC, CrisTofani requested changes

2020-12-22 15:56 UTC, CrisTofani commented on ts/features/bonus/bpd/components/BpdLastUpdateComponent.tsx
> +    if (props.potLastUpdate.kind !== potState) {
May you leave a comment to explain why this is needed?

2020-12-28 11:06 UTC, fabriziofff requested changes
This pr lgtm, I've just created another story https://www.pivotaltracker.com/story/show/176291567 to solve the flash of the bpd card, but we need to merge both this pr and #2639

2020-12-28 11:47 UTC, fabriziofff approved these changes

2020-12-28 13:48 UTC, CrisTofani approved these changes

2020-12-28 13:51 UTC, merged