[#176192263] New symbols for cashback state
pagopa/io-app pull request #2624
Opened 2020-12-21 15:42 UTC by debiff

## Short description
This PR update the symbols used in the bpd preview card e in the bpd card detail as follow:
- if the status is `Active` or `Closed` is shown the: 
  - **Closed lock** icon if the minimum transaction number isn't reached
  - **Open lock** icon if the minimum transaction number is reached but the maximum cashback amount isn't reached
  - **Fireworks** icon if the minimum transaction number and the maximum cashback are reached
- if the status is `Inactive` the behavior did not change.

## List of changes proposed in this pull request

<img src="https://user-images.githubusercontent.com/11773070/102794224-589bb480-43ab-11eb-8995-e2208616c9f4.png" width=300> <img src="https://user-images.githubusercontent.com/11773070/102794258-681afd80-43ab-11eb-9ff7-3f105008507a.png" width=300> 

<img src="https://user-images.githubusercontent.com/11773070/102794083-1ecaae00-43ab-11eb-8b3e-3c8e22fda907.png" width=300> <img src="https://user-images.githubusercontent.com/11773070/102794141-35710500-43ab-11eb-9439-af8832f5de7c.png" width=300> 

<img src="https://user-images.githubusercontent.com/11773070/102793841-c1cef800-43aa-11eb-9fe1-88a13f929588.png" width=300> <img src="https://user-images.githubusercontent.com/11773070/102793904-d7442200-43aa-11eb-883f-493cbfe7181c.png" width=300>

2020-12-22 15:33 UTC, CrisTofani requested changes

2020-12-22 15:33 UTC, CrisTofani commented on ts/features/bonus/bpd/components/bpdCardComponent/BpdCardComponent.tsx
> +    <Image
Since PR #2630 we added this as an icon `io-fireworks`, maybe we may uniform the code using the icon instead of image i guess 😉

2020-12-28 11:57 UTC, Undermaken approved these changes

2020-12-28 12:15 UTC, CrisTofani approved these changes

2020-12-28 12:16 UTC, merged