[175900141] Added profile deletion abort tracking
pagopa/io-app pull request #2649
Opened 2020-12-28 14:24 UTC by DavideValdo

## Short description
MixPanel should track whenever a user aborts the account deletion process.

## How to test
- Go to Profile -> Information ... -> Delete your account
- Follow the procedure and restart the app
- Upon restarting, click "Cancel deletion" on the dialog
- The event should be tracked on MixPanel

2020-12-28 17:16 UTC, debiff requested changes

2020-12-28 17:16 UTC, debiff commented on ts/store/middlewares/analytics.ts
> +    case getType(deleteUserDataProcessing.request):
Can you track also the `deleteUserDataProcessing.success` and the `deleteUserDataProcessing.failure` actions?

2020-12-31 09:50 UTC, debiff approved these changes

2020-12-31 10:02 UTC, Undermaken approved these changes

2020-12-31 10:02 UTC, merged