[176097298] card showing the bottom borders
pagopa/io-app pull request #2653
Opened 2020-12-28 23:44 UTC by qesya

## Short description
implements on the credit cards, the same style as for the bancomat card
![Screenshot 2020-12-29 at 00 37 37](https://user-images.githubusercontent.com/8376065/103249319-e446af80-496e-11eb-9e10-e9e217701f29.png)

2020-12-29 09:14 UTC, thisisjp commented
@qesya @Undermaken the card should have the same aspect ratio of the PagoBANCOMAT card; I guess the shorter height here is due to the lack of the Bank logo. Is there a way to have all the cards (credit, bancomat, other methods) looking the same? Thanks :)

2021-01-04 08:16 UTC, Undermaken requested changes
https://github.com/pagopa/io-app/pull/2653#issuecomment-752006230
I guess it should be fixes

2021-01-20 10:05 UTC, qesya commented
> @qesya @Undermaken the card should have the same aspect ratio of the PagoBANCOMAT card; I guess the shorter height here is due to the lack of the Bank logo. Is there a way to have all the cards (credit, bancomat, other methods) looking the same? Thanks :)

just updated, thanks for the tip

2021-01-25 19:07 UTC, debiff requested changes

2021-01-25 19:07 UTC, debiff commented on ts/screens/wallet/TransactionsScreen.tsx
> +        <View style={styles.cardBox}>
There is a problem on android
<img src="https://user-images.githubusercontent.com/11773070/105753204-978fcd80-5f48-11eb-8592-2b843256ff72.png" width=300>
You can try to use the same solution of: https://github.com/pagopa/io-app/blob/4e4e1b6640f0d8f996debf3411b86f86456f1030/ts/features/wallet/component/BaseCardComponent.tsx#L63

2021-02-04 10:25 UTC, debiff requested changes

2021-02-04 10:25 UTC, debiff commented on ts/components/wallet/card/CardComponent.style.ts
> +    // iOS and Andorid card shadow
This comment seems wrong

2021-02-04 10:25 UTC, debiff commented on ts/components/wallet/card/CardComponent.style.ts
> +    backgroundColor: variables.brandGray,
Repeated prop. Already present in `card` class
```suggestion
```

2021-02-04 10:25 UTC, debiff commented on ts/components/wallet/card/CardComponent.style.ts
> +    borderRadius: 8,
Same as `backgroundColor`

2021-02-04 10:25 UTC, debiff commented on ts/components/wallet/card/CardComponent.style.ts
> +    borderBottomLeftRadius: 8,
Why do you use both `borderBottomLeftRadius`/`borderBottomRightRadius` and `borderRadius`?

2021-02-04 16:41 UTC, debiff approved these changes

2021-02-04 16:48 UTC, merged