[#176248270] Fixes the misalignment on cashback value
pagopa/io-app pull request #2659
Opened 2020-12-29 15:17 UTC by CrisTofani

## Short description
This PR fixes the bad alignment on cashback values when multiple cards are displayed

### Before
<image src="https://user-images.githubusercontent.com/3959405/103293996-3defbe00-49f1-11eb-8f1b-451c47c45953.png"/>

### After
<image src="https://user-images.githubusercontent.com/3959405/103293949-244e7680-49f1-11eb-8437-ed3316d8cff8.png" height="550"/>

2020-12-29 16:08 UTC, debiff requested changes
There is still some problem in android with 4 digits
<img src="https://user-images.githubusercontent.com/11773070/103296456-6b8b3600-49f6-11eb-9e5a-20b586cbff02.png" width=300>

2020-12-29 17:28 UTC, CrisTofani commented
> There is still some problem in android with 4 digits
> <img alt="" width="300" src="https://user-images.githubusercontent.com/11773070/103296456-6b8b3600-49f6-11eb-9e5a-20b586cbff02.png">

nice catch! fixed in 64bbfb3

<img src="https://user-images.githubusercontent.com/3959405/103302303-9cbe3300-4a03-11eb-9509-e6eeb8508726.png" height="550"/>

2020-12-29 17:35 UTC, debiff approved these changes

2020-12-30 12:11 UTC, Undermaken approved these changes

2020-12-30 14:11 UTC, merged