[#176225603] PSP Icon removal
pagopa/io-app pull request #2690
Opened 2021-01-08 19:10 UTC by DavideValdo

## List of changes proposed in this pull request
- Removed the capability to display the PSP icon within the card

## How to test
See the missing icon in the bottom right corner when choosing the card

https://user-images.githubusercontent.com/26572302/104054520-92631c80-51ed-11eb-8b2e-9e84ad204851.mov

2021-01-08 23:24 UTC, thisisjp reviewed
The screencast looks good to me! I guess you removed it from ```ConfirmPaymentMethodScreen``` too 👍

2021-01-14 14:31 UTC, debiff requested changes

2021-01-14 14:31 UTC, debiff commented on ts/components/wallet/card/CardComponent.tsx
> +      if (type === "Picking" || type === "Full") {
What do you think about using a switch? 
It's safer, and prevent unexpected behaviour if in future we add a type (if you don't use the default of course).
```suggestion
      switch (type) {
        case "Picking":
        case "Full":
          return null;
        case "Header":
        case "Preview":
          return (
            <View style={[styles.cardLogo, { alignSelf: "flex-end" }]}>
              <Logo item={creditCard} />
            </View>
          );
      }
```

2021-01-14 14:31 UTC, debiff commented on ts/components/wallet/card/CardComponent.tsx
>      const getBodyIcon = () => {
Can you add a comment please?

2021-01-15 08:45 UTC, debiff approved these changes

2021-01-15 09:05 UTC, merged