[#176176848] Added explanatory bottom sheet for in-app payments card section
pagopa/io-app pull request #2709
Opened 2021-01-11 16:10 UTC by DavideValdo

https://user-images.githubusercontent.com/26572302/104206448-d5accd80-542f-11eb-9fb1-f50c4a4ef56c.mov

2021-01-11 16:25 UTC, thisisjp requested changes
I made some small copy changes :)

2021-01-11 16:25 UTC, thisisjp commented on locales/en/index.yml
> +        bottomSheetTitle: What are in app payments?
```suggestion
        bottomSheetTitle: What does in-app payment mean?
```

2021-01-11 16:25 UTC, thisisjp commented on locales/en/index.yml
> +        bottomSheetBody: IO lets you pay all pagoPA notices, even those on paper. If you wish, you can use this payment method. Anyhow, no in app payment will be triggered without your explicit conse
```suggestion
        bottomSheetBody: With IO you can pay all pagoPA notices, even those on paper. When you perform in-app payments, you'll need to authorize the transaction using your biometrics or the unlock code.
```

2021-01-11 16:25 UTC, thisisjp commented on locales/it/index.yml
> +        bottomSheetBody: IO ti permette di pagare tutti gli avvisi pagoPA, anche quelli cartacei. Se lo desideri, puoi usare questo metodo di pagamento. In ogni caso, nessun pagamento in app verrà ef
```suggestion
        bottomSheetBody: IO ti permette di pagare tutti gli avvisi pagoPA, anche quelli cartacei. Quando effettui un pagamento in app, ti verrà chiesto di autorizzarlo tramite riconoscimento biometrico o codice di sblocco.
```

2021-01-14 08:29 UTC, CrisTofani requested changes

2021-01-14 08:29 UTC, CrisTofani commented on ts/features/wallet/component/PagoPaPaymentCapability.tsx
> +    <TouchableOpacity onPress={present}>
imho in this case there's no need to use a component from 3rd party library, let's use `TouchableDefaultOpacity` from `ts/components/TouchableDefaultOpacity.tsx` which is based on `TouchableOpacity` from `react-native` package

2021-01-14 08:59 UTC, CrisTofani approved these changes

2021-01-14 13:51 UTC, merged