[#176434157] Remove payment CTA and expired badge
pagopa/io-app pull request #2741
Opened 2021-01-20 16:03 UTC by Undermaken

## Short description
This PR removes these element from the message list item

- payment CTA
- expired (expired & not paid payment advice) badge

| before  | now |
| ------------- | ------------- |
![before](https://user-images.githubusercontent.com/822471/105201640-5d39c100-5b41-11eb-82d3-d2c13906b07d.png) | ![now](https://user-images.githubusercontent.com/822471/105201664-6591fc00-5b41-11eb-9a6d-71b1dd1238ac.png)

2021-01-20 16:51 UTC, thisisjp approved these changes

2021-01-20 16:53 UTC, thisisjp requested changes
@Undermaken could we have the same height logic whether the list item has a CTA or not? I see some inconsistencies when the CTA is missing: the space between title and the bottom grey line is not needed

2021-01-21 09:21 UTC, Undermaken commented
> @Undermaken could we have the same height logic whether the list item has a CTA or not? I see some inconsistencies when the CTA is missing: the space between title and the bottom grey line is not needed

I fixed some UI logics where the app renders a spacer also if the content is empty. I updated the PR description with the last new screens

2021-01-21 09:22 UTC, thisisjp approved these changes

2021-01-21 13:39 UTC, debiff approved these changes

2021-01-21 13:39 UTC, merged