[#176614756] Use @pagopa packages from npm registry
pagopa/io-app pull request #2754
Opened 2021-01-26 12:05 UTC by balanza

## Short description
Remove the need to use authenticated package registry on Github by switching to public, default Npm registry.
This task is part of a broader activity to move all packaged developed by us to our Npm organization, and to have them scoped under `@pagopa` namespace.

## List of changes proposed in this pull request
- remove `.npmrc` pointing to Github registry
- update `@pagopa/react-native-cie`. Please note that version 1.x has no differences with the previous 0.x but the registry on which is published. 

## How to test
Passing build on both Android and iOS would be enough: code isn't changed, so I assume it either builds or not.
Then, we might want to manually test CIE auth.

2021-01-28 08:14 UTC, Undermaken commented
@balanza Could you update the file [README.md](https://github.com/pagopa/io-app/blob/master/README.md) `Dependencies / module for CIE authentication IO` too?

2021-01-28 09:25 UTC, balanza commented
> @balanza Could you update the file [README.md](https://github.com/pagopa/io-app/blob/master/README.md) `Dependencies / module for CIE authentication IO` too?

done

2021-02-01 17:03 UTC, Undermaken requested changes

2021-02-01 17:03 UTC, Undermaken commented on README.md
>  This package is hosted on [Github Packages](https://github.com/features/packages). In order to install this package you need to be able to access the github registry.
```suggestion
```
Could also these sentences be removed?

2021-02-01 17:07 UTC, Undermaken commented
@balanza 
maybe should we also update the `packages.json`

from `"@pagopa/react-native-cie": "0.3.3"`
to `"@pagopa/react-native-cie": "1.0.2"`

![Schermata 2021-02-01 alle 18 06 42](https://user-images.githubusercontent.com/822471/106492511-489de700-64b8-11eb-9e19-b7b27b32360f.png)

2021-02-01 17:18 UTC, balanza commented
yes of course

2021-02-01 17:27 UTC, Undermaken requested changes
@balanza it seems to miss several files when install this package via npm

![Schermata 2021-02-01 alle 18](https://user-images.githubusercontent.com/822471/106494817-307b9700-64bb-11eb-968e-32440f1fdd3f.jpg)

2021-02-01 21:19 UTC, balanza commented
Thanks for the screenshot, it's very helpful. I think I fixed it in https://github.com/pagopa/io-app/pull/2754/commits/4b585edd1e7dd5b38570bc656181537dbbf0ca6e, please double check.

2021-02-02 08:15 UTC, Undermaken approved these changes
@balanza Thank you, it works!
Could you double check my last commit https://github.com/pagopa/io-app/pull/2754/commits/42f6a34ab57b5a86288527e6c1a369d642ea3f35 ?

2021-02-02 08:46 UTC, merged