[#175800057] Added CTA to enroll a new card when card is expired/Fixed card expiration check
pagopa/io-app pull request #2779
Opened 2021-02-03 19:35 UTC by DavideValdo

## List of changes proposed in this pull request
- The card is now properly shown as expired
- A CTA opens a flow to enroll a new card

## How to test
1 - Change each `faker.date.future()` to `.past()` in `mock-server/src/payloads/wallet_v2.ts`
2 - Open the card and follow the CTA
https://user-images.githubusercontent.com/26572302/106799152-3316f180-665f-11eb-936b-741ad5359163.mov
3 - Open the PagoBANCOMAT card and follow the CTA
https://user-images.githubusercontent.com/26572302/106799203-43c76780-665f-11eb-9b24-f656bcf59851.mov

2021-02-04 10:24 UTC, thisisjp commented
@DavideValdo my bad, the "delete this method" button at the bottom of the screen is part of this story :) 

+ could you please make the (!) icon same size as the other screens? You can check the InfoBox in UI Showroom as a benchmark.
+ there's some margin missing between the infobox and the CTA. Please check the prototype for the right specs

2021-02-04 16:16 UTC, DavideValdo commented
@thisisjp https://github.com/pagopa/io-app/pull/2771 Should we wait for this to be merged then? I had done the button-related work but removed it as I realized it was another's PR matter

2021-02-04 16:18 UTC, thisisjp commented
@DavideValdo yes, the story needs those 3 points to be fixed

2021-02-04 16:34 UTC, DavideValdo commented
@thisisjp Hope it looks better like this, should I also remove the `+` icon next to the CTA that I put in the mix by mistake?

<img width="485" alt="Schermata 2021-02-04 alle 17 33 31" src="https://user-images.githubusercontent.com/26572302/106924288-379ae300-670f-11eb-8ee8-2aa9efcae02b.png">

2021-02-04 17:15 UTC, thisisjp commented
@DavideValdo yes please, let's stick to the prototype 🙏 Is the font-size within the button same size as the other ones? It looks smaller—am I wrong? 🤔

2021-02-04 17:34 UTC, DavideValdo commented
I actually copied the button from the services' list, I don't really see a different size. Maybe you're seeing a difference between the simulator's font antialiasing and the UI prototype.

2021-02-09 17:08 UTC, Undermaken requested changes

2021-02-09 17:08 UTC, Undermaken commented on ts/utils/dates.ts
> +  const date = endOfMonth(`${expireMonth}/01/${expireYear}`);
Maybe this fixes also this bug https://www.pivotaltracker.com/story/show/176870138
Could you add some other test to check if it works both with year in 2 and 4 digits?
ex
`isExpired(3, 20)` should be the same of `isExpired(3, 2020)`

2021-02-09 17:08 UTC, Undermaken commented on ts/utils/wallet.ts
> +  return isExpired(Number(expireMonth), Number(expireYear));
this function changes the previous behavior:

> // if we can't decode month or year value, card will be considered as expired

If you run this test

`expect(isExpired(Number("AAA"), Number("BBB"))).toBe(true);`

it fails

2021-02-10 16:19 UTC, DavideValdo commented on locales/it/index.yml
> +  expiredCard: Carta scaduta il
There are none, I double-checked

2021-02-10 16:20 UTC, DavideValdo commented on ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
> +  const cardIsExpired = bancomat
Are you ok with still destructuring and take advantage of `CreditCardExpirationMonth.is` for strings in `isExpiredCard` and just a false check for `NaN` in `isExpired`?

2021-02-10 20:19 UTC, DavideValdo commented on locales/it/index.yml
> +  expiredCard: Carta scaduta il
There are none, I double-checked

<img width="285" alt="Screenshot 2021-02-10 at 21 18 42" src="https://user-images.githubusercontent.com/26572302/107566810-9b2c8100-6be5-11eb-914e-767ecdd9eb0b.png">

2021-04-15 08:34 UTC, closed without merging