[#176575120] Graphical refactor entry point co-badge
pagopa/io-app pull request #2783
Opened 2021-02-04 16:32 UTC by debiff

## Short description
This PR align the bancomat detail screen with the design.

## List of changes proposed in this pull request
- Refactor `BancomatInformation` component
- Added `BancomatInformationBottomSheet` component
- Insert `BancomatInformationBottomSheet` in `NewMethodAddedNotifier` component

https://user-images.githubusercontent.com/11773070/106922018-e25dd200-670c-11eb-868c-e1652a3c3680.mov

2021-02-04 17:47 UTC, thisisjp requested changes
I made some small changes on copy

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +        description: "This question allows us to better understand what your card is like and help you add it to your Wallet."
```suggestion
        description: "This allows us to better identify your card and help you add it to your Wallet."
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            title: "I do not know"
```suggestion
            title: "I don't know"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            title: "No, I only use it in shops"
```suggestion
            title: "No, I only use it for in-store purchases"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            title: "Yes, it is enabled for online purchases"
```suggestion
            title: "Yes, it works online"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            description: "The data will be verified in the way appointed by your bank, for example via text message or app."
```suggestion
            description: "We'll verify card data with your bank, usually with an SMS or a push notification"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/it/index.yml
> +            description: "I dati verranno verificati con le modalità previste dalla tua banca, ad esempio via sms o app."
```suggestion
            description: "Verificheremo i dati della carta con la tua banca, di solito via sms o notifica push"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            description: "We will look for all the cards in your name at the banks participating in the service."
```suggestion
            description: "We will search for all cards registered to you at participating banks"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +            description: "We will look for all the cards in your name at the banks participating in the service."
```suggestion
            description: "We will search for all cards registered to you at participating banks"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/en/index.yml
> +        body: "If your PagoBANCOMAT card shows other international circuits, you can add them by searching for all debit (or credit) cards in your name. By activating the Cashback method, you can als
```suggestion
        body: "If your PagoBANCOMAT card shows other international circuits, you can add them by searching for all debit (or credit) cards registered to you. When you enable Cashback on this method, you will also be able to collect transactions on these circuits."
```

2021-02-04 17:47 UTC, thisisjp commented on locales/it/index.yml
> +            description: "Cercheremo tutte le carte intestate a te presso le banche aderenti al servizio."
```suggestion
            description: "Cercheremo tutte le carte intestate a te presso le banche aderenti al servizio"
```

2021-02-04 17:47 UTC, thisisjp commented on locales/it/index.yml
> +            description: "Cercheremo tutte le carte intestate a te presso le banche aderenti al servizio."
```suggestion
            description: "Cercheremo tutte le carte intestate a te presso le banche aderenti al servizio"
```

2021-02-08 19:26 UTC, fabriziofff requested changes

2021-02-08 19:26 UTC, fabriziofff commented on ts/features/wallet/bancomat/screen/BancomatInformation.tsx
> -);
In my understanding `hideCobrandTitle` is not used anymore. If this is the case, how about removing it from the props?

2021-02-08 19:26 UTC, fabriziofff commented on ts/features/wallet/component/NewMethodAddedNotifier.tsx
> +  const { present } = BancomatInformationBottomSheet(
```suggestion
  const { present } = bancomatInformationBottomSheet(
```
To keep consistency in the codebase, we use `PascalCase` for components and types, `camelCase` for functions and const.

2021-02-08 19:26 UTC, fabriziofff commented on ts/features/wallet/bancomat/screen/BancomatInformation.tsx
> +  const { present } = BancomatInformationBottomSheet(props.onAddPaymentMethod);
```suggestion
  const { present } = bancomatInformationBottomSheet(props.onAddPaymentMethod);
```

To keep consistency in the codebase, we use `PascalCase` for components and types, `camelCase` for functions and const.

2021-02-09 14:00 UTC, fabriziofff approved these changes

2021-02-09 14:13 UTC, merged