[#176268541] The reason and the abiCode of bpdTransactionsLoad.failure it was not tracked
pagopa/io-app pull request #2819
Opened 2021-02-12 09:45 UTC by fabriziofff

## Short description
This pr adds the missing information to the tracking of the event `bpdTransactionsLoad.failure`

2021-02-16 17:02 UTC, debiff requested changes

2021-02-16 17:02 UTC, debiff commented on ts/features/bonus/bpd/analytics/index.ts
> +        awardPeriodId: action.payload,
This shouldn't be:
```suggestion
        awardPeriodId: action.payload.awardPeriodId,
```
?

2021-02-18 10:34 UTC, fabriziofff commented on ts/features/bonus/bpd/analytics/index.ts
> +        awardPeriodId: action.payload,
Yes it should 😄

2021-02-18 12:56 UTC, debiff approved these changes

2021-02-18 12:56 UTC, merged