[#176981388] Credit card onboarding attempt: save info about 3DS2
pagopa/io-app pull request #2858
Opened 2021-03-02 14:28 UTC by Undermaken

## Short description
wip

2021-03-08 10:03 UTC, debiff requested changes

2021-03-08 13:31 UTC, Undermaken commented on ts/utils/payment.ts
> +  const maybeCutcomecodeKey = OutcomeCodesKey.decode(outcomeCode);
Thanks!
I also refactored this function
https://github.com/pagopa/io-app/pull/2858/commits/5e68af5dd4aebd105cdf3a00ec0901a30042d7ed

2021-03-08 13:37 UTC, Undermaken commented on ts/store/actions/wallet/wallets.ts
> +export const creditCardPaymentNavigationUrls = createStandardAction(
Done in https://github.com/pagopa/io-app/pull/2858/commits/4b9b3ca9ff9232a8a3cc86cb6d7d1155cc0e4bb4

2021-03-09 08:55 UTC, debiff approved these changes

2021-03-09 08:56 UTC, merged