[#177270155]: improve accessibility flow on add card screen
pagopa/io-app pull request #2942
Opened 2021-03-26 11:49 UTC by nicola-bitrocketdev

## Improvement of the accessibility flow in the add card section

Based on a report from a user who reports a bad user experience on the accessibility side, the following changes have been made as agreed with the part that deals with UX

## List of changes proposed in this pull request (all changes are referenced only when Talkback / VoiceOver is on)
- Removal of **_placeholders_** in the input fields as useless for a blind person and due to the current limitation of react-native in the area of ​​accessibility, to manage hints with placeholders
- When present, the **_description text_** below the input field will be ignored. Instead, it will be read as an additional hint when you click on in the input field
- When clicking on the **_label_** of the input field, after reading the text it will also be said "Header"
- When clicking on the **_input field_**, it will read the label of the field as the base hint
- When clicking on a **_link_**, after reading the text it will also be said "Link"
- When clicking on a **_data_ _field_**, it will read the label and it will also be read "2 digits for the month, 2 for the year"
- When clicking on **_secure code_,** it will read the label and it will also be read "3 digits (or 4 digits depending on the type of credit card)"
- When clicking on **_disabled button_**, in addition to what it reads by default, it now reads even if the button is disabled.

## Sviluppato e testato con TalkBack
It is necessary to test how everything responds on IOS

2021-04-02 08:41 UTC, Undermaken requested changes

2021-04-07 12:54 UTC, ncannata-dev commented on ts/screens/wallet/AddCardScreen.tsx
> +  const placeholderCard = isScreenReaderEnabled
Fixed as suggested ✅

2021-04-07 12:54 UTC, ncannata-dev commented on ts/components/LabelledItem.tsx
> +              accessibilityHint={`${this.props.accessibilityHint}, ${
Fixed as suggested ✅

2021-04-07 12:54 UTC, ncannata-dev commented on ts/components/LabelledItem.tsx
> +              accessibilityHint={`${this.props.accessibilityHint}, ${
Fixed as suggested ✅

2021-04-13 13:35 UTC, Undermaken commented
@ncannata-dev this PR is still WIP (fixing iOS accessibility), right?
If yes could you move it in draft state until it is not ready?

2021-04-14 07:15 UTC, ncannata-dev commented
> @ncannata-dev this PR is still WIP (fixing iOS accessibility), right?
> If yes could you move it in draft state until it is not ready?
 
Sure!

2021-04-22 08:08 UTC, Undermaken approved these changes

2021-04-22 08:11 UTC, Undermaken approved these changes

2021-04-22 08:15 UTC, merged