[#177560087] Changed pick psp screen UI
pagopa/io-app pull request #2954
Opened 2021-04-01 08:42 UTC by andrea-favaro

## Short description
Integrated new Figma UI in PickPspScreen and added service name if there is an error on loading provider image

## How to test
Move into PickPspScreen and check if it is similar to the new UI version in Figma

2021-04-01 10:39 UTC, thisisjp commented
@andrea-favaro could you please attach a video showing the performed changes?

2021-04-01 13:57 UTC, andrea-favaro commented
> @andrea-favaro could you please attach a video showing the performed changes?

@thisisjp [Video](https://user-images.githubusercontent.com/61834253/113304583-78276f00-9302-11eb-9136-186b572dea42.mp4
)

2021-04-02 13:58 UTC, debiff requested changes

2021-04-02 13:58 UTC, debiff commented on ts/components/core/typography/LabelSmall.tsx
> +type AllowedWeight = Extract<IOFontWeight, "Bold" | "Regular">;
In this case you can use `H5` component instead.

2021-04-02 13:58 UTC, debiff commented on ts/screens/wallet/payment/PickPspScreen.tsx
> +        <Content noPadded>
What do you think about use a `SafeAreaView` component instead? 
```suggestion
        <SafeAreaView style={IOStyles.flex}>
```

2021-04-02 13:58 UTC, debiff commented on ts/screens/wallet/payment/PickPspScreen.tsx
> +        <FooterWithButtons type="SingleButton" leftButton={backButtonProps} />
There is already a function that returns the props you set in `backButtonProps`. Can you use it?
```suggestion
        <FooterWithButtons
            type="SingleButton"
            leftButton={cancelButtonProps(
              this.props.navigateBack,
              I18n.t("global.buttons.back")
            )}
          />
```

2021-04-02 13:58 UTC, debiff commented on ts/screens/wallet/payment/PickPspScreen.tsx
> +          {!this.state.hasImageLoadingError ? (
There is a problem in the way you check if an image has an error.

The state is the same for all the items you generate, so if 1 of the images is not reachable also all the others doesn't show the image.

What about using the `useImageResize` utils:
```suggestion
         {useImageResize(BASE_IMG_W, BASE_IMG_H, item.logoPSP).fold(
          <Body>{item.businessName}</Body>,
          size => {
            const imageStyle: StyleProp<ImageStyle> = {
              width: size[0],
              height: size[1],
              resizeMode: "contain"
            };
            return (
              <Image
                style={imageStyle}
                resizeMode="contain"
                source={{ uri: item.logoPSP }}
              />
            );
          }
        )}
```
Of course being a hook you should convert the in component in a function component.

2021-04-12 11:06 UTC, debiff commented
@thisisjp If the psp upload fails for any reason (eg 500 - server error) is this the expected behavior?

https://user-images.githubusercontent.com/11773070/114385057-cacd1a80-9b8f-11eb-9f82-63175ed4560b.mov

If not, what we can show?

2021-04-12 11:21 UTC, debiff requested changes

2021-04-12 11:21 UTC, debiff commented on ts/components/PspComponent.tsx
> +        {psp.logoPSP && imageStyle ? (
Seems this check is duplicated. If `psp.logoPSP` is undefined `useImageResize` is `left` so `imageStyle` already has this information.
```suggestion
        {imageStyle ? (
```
Do you agree?

2021-04-12 11:21 UTC, debiff commented on ts/components/PspComponent.tsx
> +import React, { FC } from "react";
What do you think to about moving this component in `ts/components/wallet/payment/PspComponent.tsx`

2021-04-12 14:05 UTC, thisisjp commented
@debiff I guess since we haven't introduced any new logic in this issue, we've never faced this "empty state" scenario before, right? Can we use the well-known "umbrella" screen with the retry button? 😄  ☔

2021-04-13 13:07 UTC, debiff commented
> @debiff I guess since we haven't introduced any new logic in this issue, we've never faced this "empty state" scenario before, right? Can we use the well-known "umbrella" screen with the retry button? 😄 ☔

@thisisjp No problem for me! What do you think about uniforming also the loading behaviour? At the moment, as you can see in the video, there is semi-transparent overlay while in many other situation we used a screen like this:
<img src="https://user-images.githubusercontent.com/11773070/114557360-e1e03b00-9c69-11eb-8ee8-c196e93d99da.png" width=300>

2021-04-21 10:15 UTC, debiff approved these changes

2021-04-21 10:15 UTC, merged