[#177161429] Fixed missing loading on delete credit card
pagopa/io-app pull request #2980
Opened 2021-04-13 13:01 UTC by andrea-favaro

## Short description
Show loading when canceling a credit card.

**After clicking this delete button**
<img width="300" alt="Screenshot 2021-04-13 at 14 50 33" src="https://user-images.githubusercontent.com/61834253/114555226-c83df400-9c67-11eb-8123-cdf9df86e27a.png">

**A loading page like this will be shown**
<img width="300" alt="Screenshot 2021-04-13 at 14 56 01" src="https://user-images.githubusercontent.com/61834253/114555902-721d8080-9c68-11eb-8815-f01dfa7b53c8.png">

## How to test
Move into credit card detail and try to delete it. I suggest you to add a delay in dev server to slow down the deletion process and be able to properly observe the loading behavior

2021-04-14 10:01 UTC, debiff requested changes

2021-04-14 10:01 UTC, debiff commented on ts/screens/wallet/TransactionsScreen.tsx
>    return (
Can this reduce your code size?
```suggestion
  return props.isLoadingDelete ? (
    <LoadingErrorComponent
      isLoading={props.isLoadingDelete}
      loadingCaption={I18n.t("cardComponent.deleteLoading")}
      onRetry={onRetry}
    />
  ) : (
```

2021-04-15 08:45 UTC, debiff requested changes

2021-04-15 08:45 UTC, debiff commented on ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
> +      {props.isLoadingDelete ? (
There is a reason why this fragment is used? Can we remove it in your opinion?
```suggestion
    props.isLoadingDelete ? (
```
If for you make sense the same is in the other payment methods screen.

2021-04-15 08:45 UTC, debiff commented on ts/features/wallet/bancomat/screen/BancomatDetailScreen.tsx
> +    </>
Connected to the above comment:
```suggestion
      )
```

2021-04-28 12:33 UTC, debiff approved these changes
This PR lgtm. 
@fabriziofff can you double check it? 
@andrea-favaro can you solve the conflicts please?

2021-04-29 12:59 UTC, fabriziofff commented
@debiff sure, I wait for the conflict resolution and do a complete check.

2021-05-04 08:19 UTC, andrea-favaro commented
> This PR lgtm.
> @fabriziofff can you double check it?
> @andrea-favaro can you solve the conflicts please?

@fabriziofff conflict solved

2021-05-04 11:03 UTC, fabriziofff approved these changes

2021-05-04 11:04 UTC, merged