[#177536180] Handle logout delay
pagopa/io-app pull request #2990
Opened 2021-04-19 15:40 UTC by Undermaken

## Short description
This PR adds a screen to show the logout loading
It also removes some dead code :skull:

### before
https://user-images.githubusercontent.com/822471/115264125-4ef64380-a136-11eb-813c-6fe363e32f3b.mov

### now
https://user-images.githubusercontent.com/822471/115264138-5289ca80-a136-11eb-993f-43f1b3c6e518.mov

2021-04-19 16:47 UTC, thisisjp requested changes
Good catch! Here's also some gender-neutral copy fixes ;)

2021-04-19 16:47 UTC, thisisjp commented on locales/en/index.yml
>      menulabel: Logout from IO
```suggestion
    menulabel: Do you want to logout?
```

2021-04-19 16:47 UTC, thisisjp commented on locales/en/index.yml
>      alertMessage: Are you sure you want to quit? The next time you log in you will need a new login with CIE or SPID.
```suggestion
    alertMessage: If you want to login again, you'll need to authenticate using CIE or SPID.
```

2021-04-27 07:45 UTC, fabriziofff approved these changes
This pr LGTM, but I noticed a behavior, not strictly related to this PR.
If there is no connectivity with the backend or if any error occurr (response `500`), the user is able to complete the logout even if communication with the remote endpoint has not occurred. Is this the expected behavior?

2021-04-27 08:04 UTC, Undermaken commented
> This pr LGTM, but I noticed a behavior, not strictly related to this PR.
> If there is no connectivity with the backend or if any error occurr (response `500`), the user is able to complete the logout even if communication with the remote endpoint has not occurred. Is this the expected behavior?

Yes it is. It is not the best but it was a choice: user can logout even if the backend doesn't respond.
More details about this are reported in the `ts/components/screens/LogoutScreen.tsx` component description

2021-04-27 08:12 UTC, fabriziofff commented
ok, i was just wondering if it was correct from a server point of view. If it needs this information to update data (for example, don't send any notifications after logout) it would create an inconsistent state.

2021-04-27 08:15 UTC, Undermaken commented
> ok, i was just wondering if it was correct from a server point of view. If it needs this information to update data (for example, don't send any notifications after logout) it would create an inconsistent state.

This is a good point to discuss with backend & design.
I opened a bug https://www.pivotaltracker.com/story/show/177923188

2021-04-28 10:37 UTC, merged