178065380 chore removed failed identification
pagopa/io-app pull request #3044
Opened 2021-05-14 08:47 UTC by andrea-favaro

## Short description
Replaced "Identification failed" text that shows if you fail the biometric identification and wrong code error text.
Now you will see a generic "Try again" for both errors.

## How to test
Try to unlock the app, in the identification modal component, if biometry state is in failure state or if you fail to write the unlock code you should see "Try again" text.
if you fail to write the unlock code more than 4-5 times you should see "Try again. Number of remaining attempts" text.

**Before:**
<img width="300" alt="Screenshot 2021-05-14 at 10 31 21" src="https://user-images.githubusercontent.com/61834253/118245499-2ea17680-b4a1-11eb-8f28-ab29fee497e9.png">

**After:**
<img width="300" alt="Screenshot 2021-05-14 at 10 45 15" src="https://user-images.githubusercontent.com/61834253/118245861-92c43a80-b4a1-11eb-8b5b-707f8e6b720f.png">

2021-05-14 08:51 UTC, thisisjp approved these changes

2021-05-17 09:31 UTC, debiff requested changes

2021-05-17 09:31 UTC, debiff commented on ts/screens/modal/IdentificationModal.tsx
> +  private getErrorText = () => {
Could you please write a comment by making explicit when we can see the retry message or not?

2021-05-19 12:46 UTC, debiff approved these changes

2021-05-19 13:06 UTC, merged