[IAGP-57] Change locales for photolibrary permission
pagopa/io-app pull request #3120
Opened 2021-06-09 16:42 UTC by fabriziofff

## Short description
This pr changes the locales for the photo library permission.

Before            |  After
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/26501317/121395008-3d6d3300-c952-11eb-8d55-3a06b883c187.png" width="300">|  <img src="https://user-images.githubusercontent.com/26501317/121395049-4958f500-c952-11eb-9315-56f6a3bababd.png" width="300">

## List of changes proposed in this pull request
- Update locales
- Added @thisisjp as CODEOWNER for iOS native locales

2021-06-09 16:56 UTC, thisisjp requested changes

2021-06-09 16:56 UTC, thisisjp commented on ios/ItaliaApp/it.lproj/InfoPlist.strings
> +"NSPhotoLibraryUsageDescription" = "per salvare o caricare codici e screenshot";
```suggestion
"NSPhotoLibraryUsageDescription" = "Con IO puoi salvare bonus e certificati, o caricare screenshot e avvisi di pagamento";
```

2021-06-09 16:56 UTC, thisisjp commented on ios/ItaliaApp/Info.plist
> +    <string>to save or load codes and screenshots </string>
```suggestion
    <string>With IO you can save your bonuses and certificates, in addition to uploading screenshots or payment notices</string>
```

2021-06-09 16:56 UTC, thisisjp commented on locales/en/index.yml
> +      message: IO needs access your images to save or load codes and screenshots
```suggestion
      message: IO needs access to your gallery to save bonuses and certificates, in addition to uploading screenshots or payment notices
```

2021-06-09 16:56 UTC, thisisjp commented on locales/it/index.yml
> +      message: IO ha bisogno di accedere alle tue immagini per salvare o caricare codici e screenshot
```suggestion
      message: IO ha bisogno di accedere alla tua galleria per salvare bonus e certificati, o caricare screenshot e avvisi di pagamento
```

2021-06-09 17:14 UTC, Undermaken approved these changes

2021-06-09 17:15 UTC, Undermaken commented
@thisisjp merge on your approval

2021-06-09 20:21 UTC, thisisjp approved these changes

2021-06-11 08:09 UTC, pietro909 approved these changes

2021-06-21 13:40 UTC, merged