Update README
pagopa/io-app pull request #3122
Opened 2021-06-10 10:44 UTC by pietro909

## Short description
An update of the README based on my recent experience with the onboarding process.

 **How far did I go?** I stopped short of _Internationalization_ because I want to keep this update small and moreover I do have some opinions on how to split the docs into separate files. More on that later ⌛ 

## List of changes proposed in this pull request
- The largest update affects the _Pre-requisites_ section, where I removed the instructions for _nodenv_ and _rbenv_ in favour of a more concise reference to the tools' official website.
- Smaller updates across the file are related to missing/extra spaces, misstyped official names, missing links, extra markup.
- I'm afraid I also added a few line breaks to fit the text in my editor before turning line-wrap on. Please let me know if this is something I should revert.

## How to test
n/a

2021-06-10 15:50 UTC, Undermaken requested changes
This PR looks good to me!
Since we are, could you remove this obsolete text?

`(support ready for Android - soon for iOS)`

This sentence is not longer valid. CIE is available on both OS

2021-06-11 08:11 UTC, pietro909 commented
@Undermaken obsolete text removed in https://github.com/pagopa/io-app/pull/3122/commits/669a240e2ffdac5d0259f1aeb5198df32151cb08#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L85

2021-06-11 08:15 UTC, debiff approved these changes

2021-06-11 08:15 UTC, Undermaken approved these changes

2021-06-11 08:15 UTC, merged