[IARS-40] Removes the currentSelectedService reducer and action
pagopa/io-app pull request #3219
Opened 2021-07-12 10:46 UTC by CrisTofani

## Short description
This PR removes the currentSelectedService store section

Updated configure and persistor rule to remove persisted information

2021-07-12 14:32 UTC, pietro909 approved these changes

2021-07-13 09:43 UTC, Undermaken requested changes

2021-07-13 09:52 UTC, CrisTofani commented on ts/boot/configureStoreAndPersistor.ts
> +    };
the first point: it was a CP&Paste error, my bad! of course I mean entities 🤕

2021-07-13 09:52 UTC, CrisTofani commented on ts/boot/configureStoreAndPersistor.ts
> +    };
the second point I'm going to fix the rule

2021-07-13 11:08 UTC, Undermaken requested changes

2021-07-13 11:08 UTC, Undermaken commented on ts/boot/configureStoreAndPersistor.ts
> +  "17": (state: PersistedState) => {
you don't need this migration anymore.
It has not effect and producer an error (`entities` here is undefined)

2021-07-13 12:13 UTC, Undermaken approved these changes

2021-07-13 12:14 UTC, Undermaken commented
@pietro909 waiting your double check to the last changes
you can marge if it's good also for you

2021-07-15 08:43 UTC, CrisTofani commented
@pietro909 @Undermaken may we merge this?

2021-07-15 13:36 UTC, pietro909 approved these changes

2021-07-15 14:14 UTC, merged