[IASV-35] Add ToS component
pagopa/io-app pull request #3256
Opened 2021-07-23 13:59 UTC by Undermaken

## Short description
TBD

2021-08-02 08:11 UTC, debiff requested changes

2021-08-02 10:20 UTC, Undermaken commented on ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx
> +    props.back();
Because two is better than one 😆 
Maybe `cancel` should be enough?

2021-08-02 13:26 UTC, Undermaken commented on ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx
> +    props.back();
```suggestion
```

2021-08-02 13:26 UTC, Undermaken commented on ts/features/bonus/siciliaVola/screens/voucherGeneration/CheckStatusRouterScreen.tsx
> +    props.back();
down within https://github.com/pagopa/io-app/pull/3256/commits/e9e819229a78f6afc87eb67992fbaba6cec9d55f

2021-08-03 07:45 UTC, debiff approved these changes

2021-08-03 07:58 UTC, merged