[IA-55] Introduces Bonus Vacanze card preview accessibility label
pagopa/io-app pull request #3336
Opened 2021-08-30 14:26 UTC by CrisTofani

## Short description
This PR improves accessibility on BonusVacanze preview component

![image](https://user-images.githubusercontent.com/3959405/131354940-4ffd67d2-e1b5-459e-9d47-6feef5224199.png)

2021-08-30 16:02 UTC, thisisjp requested changes

2021-08-30 16:02 UTC, thisisjp commented on locales/it/index.yml
> +      previwew: Bonus Vacanze, massimo valore {{value}}, stato {{status}}
```suggestion
      preview: Bonus Vacanze, importo massimo {{value}}
```

2021-08-30 16:02 UTC, thisisjp commented on locales/it/index.yml
> +      previwew: Bonus Vacanze, massimo valore {{value}}, stato {{status}}
same as EN

2021-08-30 16:02 UTC, thisisjp commented on locales/it/index.yml
>        card: Il tuo Bonus Vacanze con codice {{code}}, del valore di {{value}} euro è {{status}}
```suggestion
      card: Il tuo Bonus Vacanze con codice {{code}}, del valore massimo di {{value}} euro è {{status}}
```

2021-08-30 16:02 UTC, thisisjp commented on locales/en/index.yml
>        card: Your Bonus Vacanze with code {{code}} worth {{value}} euro is {{status}}
```suggestion
      card: Your Bonus Vacanze with code {{code}} worth up to {{value}} euro is {{status}}
```

2021-08-30 16:07 UTC, CrisTofani commented on locales/en/index.yml
> +      previwew: Bonus Vacanze, worth {{value}}, status {{status}}
Since the status changes the value opacity I thought to let it read by VO what do you think?

2021-08-30 16:08 UTC, thisisjp commented on locales/en/index.yml
> +      previwew: Bonus Vacanze, worth {{value}}, status {{status}}
...I wasn't aware of that 😂

2021-08-30 16:09 UTC, thisisjp commented on locales/en/index.yml
> +      previwew: Bonus Vacanze, worth {{value}}, status {{status}}
suggestion updated

2021-08-30 16:21 UTC, thisisjp commented on locales/en/index.yml
> +      preview: Bonus Vacanze, worth up to €{{value}}, status {{status}}
```suggestion
      preview: Bonus Vacanze, worth up to {{value}} euro, {{status}}
```

2021-08-30 16:21 UTC, thisisjp commented on locales/it/index.yml
> +      preview: Bonus Vacanze, importo massimo {{value}}€, stato {{status}}
```suggestion
      preview: Bonus Vacanze, importo massimo {{value}} euro, {{status}}
```

2021-08-30 16:22 UTC, thisisjp approved these changes

2021-08-31 09:40 UTC, Undermaken approved these changes

2021-08-31 09:40 UTC, merged