[IAI-25] Replaces biometric library to support more devices biometric options
pagopa/io-app pull request #3344
Opened 2021-09-02 08:36 UTC by CrisTofani

## Short description
This PR replaces `react-native-touch-id` with `react-native-fingerprint-scanner` and updates all local implementations inside app codebase.

## How to test
Test on both physical and virtual devices to catch if any issue may occur, close the app and then try logging in through biometric recognition.

<img src="https://user-images.githubusercontent.com/3959405/131811176-af3ef152-6734-4313-9204-57273e296635.png" height="550"/>

2021-09-02 14:26 UTC, fabriziofff requested changes
Trying the new library I found the following wrong behaviors:

### Android
Prerequisite: At least one biometric active on the device, `biometric recognition` active in app settings.
1. `Profile > Security > Biometric Recognition`, if the `Biometric Recognition` is active and I try to disable the toggle, after successfully passing the biometric check, the toggle remains active.
2. Initial identification screen > Biometric prompt > Cancel, the screen shows "Retry", as if there a wrong authentication.
3. Initial identification screen > Biometric prompt > Cancel > tap on the fingerprint icon > complete the biometric identification > The screen remains and the authentitcation doesn't continue.
Cashback
4. Wallet > Cashback Card > Quit Cashback > Biometric prompt > Cancel, it is not possible to press the numeric buttons of the pin 

### iOS
✅ on iPhone 8 (TouchID) and iPhone 11 (FaceID)

2021-09-02 14:41 UTC, CrisTofani commented on ts/sagas/startup/checkAcknowledgedFingerprintSaga.ts
> +// }
yes, my miss I left it for reference during implementation

2021-09-02 15:05 UTC, CrisTofani commented on package.json
> +    "react-native-fingerprint-scanner": "^6.0.0",
e9bff9f solves

2021-09-02 15:05 UTC, CrisTofani commented on ts/sagas/startup/checkAcknowledgedFingerprintSaga.ts
> +// }
659fe5a solves

2021-09-03 13:48 UTC, fabriziofff approved these changes

2021-09-06 08:40 UTC, merged