IA-382 added a label read by screen reader
pagopa/io-app pull request #3477
Opened 2021-11-05 07:44 UTC by filippo-tenaglia

2021-11-05 08:42 UTC, thisisjp reviewed
@filippo-tenaglia we usually write these hints using the imperative verb, rather than the infinitive—check my suggested change. Sounds ok for you? 😊

2021-11-05 08:42 UTC, thisisjp commented on locales/it/index.yml
> +    switchLabel: "Selezionare per attivare"
```suggestion
    switchLabel: "Seleziona per attivare"
```

2021-11-08 08:48 UTC, pietro909 requested changes
I suggest you run `yarn tsc:noemit` on your machine to ensure that the code is building, and perform an actual test locally to verify that the PR is addressing the issue properly.

2021-11-08 08:48 UTC, pietro909 commented on ts/components/ui/Switch.tsx
> +    import { NativeBase, Switch as NBSwitch } from "native-base";
Mind the leading whitespaces :-)

2021-11-08 08:48 UTC, pietro909 commented on ts/components/ui/Switch.tsx
> +  public render(accessibleLabelText) {
The `render` function doesn't accept any argument: it should use `this.props` and `this.state` as the only input sources. This is also the reason we the build is failing.

Please see also [the official documentation](https://reactjs.org/docs/react-component.html#render).

2021-11-08 08:48 UTC, pietro909 commented on ts/components/ui/Switch.tsx
> +// this label can be a default value or received from external call
We don't usually write comments about well-known or already documented behavior (ie: how optional properties work).

2021-11-10 11:15 UTC, pietro909 approved these changes

2021-11-10 11:15 UTC, merged