[IA-532] Complete ZendeskSupportHelpCenter screen
pagopa/io-app pull request #3571
Opened 2021-12-13 08:52 UTC by debiff

## Short description
This PR complete the `ZendeskSupportHelpCenter` screen based on the UI provided.
It replicate the contextual help also for the Zendesk workflow.
The choice was to limit refactoring to a minimum trying to limit code reuse by extracting functions.

To maintain backward compatibility it was necessary to use navigation parameters.

This screen also manage the `PanicMode` case

## List of changes proposed in this pull request
- Complete `ZendeskSupportHelpCenter` screen
- Exported `getContextualHelpConfig` and `getContextualHelpData` functions and `reloadContextualHelpDataThreshold` const from `BaseScreenComponent` and `ContextualHelp` component
- Added navigation params to `zendeskSupportStart` action
- Added `ZendeskPanicMode` screen

https://user-images.githubusercontent.com/11773070/145780303-192f33ef-4ac9-4b85-998b-15c0aca021bc.mp4

https://user-images.githubusercontent.com/11773070/145780310-2cf4ee75-8ca4-45db-b5f7-8c7aaf04b58f.mp4

## How to test
Be sure to set the local `zendeskEnabled` FF to true and the remote `assistanceTool` to `zendesk` and press the assistance button (`?`)

2021-12-13 08:57 UTC, thisisjp reviewed
added new copy

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
> +      title: "Do you need help?"
```suggestion
      title: "Need help?"
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
> +      subtitle: "To request assistance or suggest an improvement, write to us: we will reply as soon as possible."
```suggestion
      subtitle: "If you need support or want to suggest an improvement, please write to us: we will get back to you as soon as possible."
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
> +      adviceMessage: "If your problem concerns the content of a message or the service of an organization, contact the latter. You will find the references within the message or in the card of the se
```suggestion
      adviceMessage: "If your problem concerns the content of a message or the service of an Institution, contact the latter. You will find the contact details within the message or in the tab of the service concerned."
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
>        contactSupport: "Contact support"
```suggestion
      contactSupport: "Write us"
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
>        seeReports: "See reports in progress"
```suggestion
      seeReports: "See your requests"
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
> +    title: "Unfortunately, we can't help you right now"
```suggestion
    title: "Sorry, we cannot help you at the moment"
```

2021-12-13 08:57 UTC, thisisjp commented on locales/en/index.yml
> +    body: "We know there is a problem and we are working to solve it. If the problem persists, or if you need assistance on another topic, please try again to write to us later."
```suggestion
    body: "We know there is a problem and we are working to solve it. If the problem remains, or if you need support on another topic, please try again later."
```

2021-12-13 08:57 UTC, thisisjp commented on locales/it/index.yml
>        contactSupport: "Contatta l'assistenza"
```suggestion
      contactSupport: "Scrivici"
```

2021-12-13 08:57 UTC, thisisjp commented on locales/it/index.yml
>        seeReports: "Vedi segnalazioni in corso"
```suggestion
      seeReports: "Vedi le tue richieste"
```

2021-12-13 08:57 UTC, thisisjp approved these changes

2021-12-13 14:22 UTC, fabriziofff requested changes

2021-12-14 13:03 UTC, debiff commented on ts/features/zendesk/screens/ZendeskPanicMode.tsx
> +import image from "../../../../img/assistance/panicMode.png";
The second option! Thank you! Removed in [6f6767f](https://github.com/pagopa/io-app/pull/3571/commits/6f6767fa5d5fe18e775d5cb415aab911db982203)

2021-12-14 13:45 UTC, fabriziofff approved these changes

2021-12-14 13:46 UTC, merged