[IA-566] Fix entrypoints on error and attempt screens
pagopa/io-app pull request #3573
Opened 2021-12-13 09:36 UTC by debiff

## THIS PR DEPENDS ON #3572 
## Short description
This PR manage the `assistanceTools` in the transaction error screen and in the detail of payment and credit card attempt.

## List of changes proposed in this pull request
- Extracted the `canShowHelp` function
- Managed the assistance tools in `TransactionErrorScreen`
- Managed the assistance tools in `PaymentHistoryDetailsScreen`
- Managed the assistance tools in `CreditCardOnboardingAttemptDetailScreen`

https://user-images.githubusercontent.com/11773070/145787436-c5eac70c-4922-4eeb-ae19-a0236b012466.mp4

https://user-images.githubusercontent.com/11773070/145787467-78f18326-801e-4137-b215-f558162d8b80.mp4

https://user-images.githubusercontent.com/11773070/145787484-a6bacef9-fcf6-4556-9f8a-2ea19742684b.mp4

## How to test
Fail to add a credit card or fail a payment and modify the assitanceTool in the [dev-server](https://github.com/pagopa/io-dev-api-server/blob/bd71dd1d55cffb23c17e34bcb8979e5bf2266b05/src/payloads/backend.ts#L198) to try the different combinations.

2021-12-13 10:16 UTC, thisisjp approved these changes
LGTM @debiff ideally users shouldn't select any category when asking help using these entry points (we already know it's a payment-related issue). Can we track this improvement in our backlog? 🙏

2021-12-15 15:11 UTC, Undermaken commented
@debiff could you solve conflicts?

2021-12-16 08:32 UTC, debiff commented
> LGTM @debiff ideally users shouldn't select any category when asking help using these entry points (we already know it's a payment-related issue). Can we track this improvement in our backlog? 🙏

Yes, this is not a great problem, we can do it! 💪

2021-12-16 08:55 UTC, debiff commented
> @debiff could you solve conflicts?

Sure, done!

2021-12-17 11:02 UTC, Undermaken requested changes

2021-12-17 11:18 UTC, debiff commented on ts/screens/wallet/creditCardOnboardingAttempts/CreditCardOnboardingAttemptDetailScreen.tsx
> +        zendeskAssistanceLogAndStart();
Added in [db6bde7](https://github.com/pagopa/io-app/pull/3573/commits/db6bde7f92699f5556ac4fc1c42dbabd879a3eb6)

2021-12-17 11:18 UTC, debiff commented on ts/screens/wallet/PaymentHistoryDetailsScreen.tsx
> +        this.zendeskAssistanceLogAndStart();
Added in [db6bde7](https://github.com/pagopa/io-app/pull/3573/commits/db6bde7f92699f5556ac4fc1c42dbabd879a3eb6)

2021-12-17 12:08 UTC, Undermaken approved these changes

2021-12-17 12:08 UTC, merged