[IA-587] Add Zendesk analytics
pagopa/io-app pull request #3601
Opened 2021-12-20 17:33 UTC by debiff

## Short description
This PR adds the track the events that happens in the Zendesk request workflow.

## List of changes proposed in this pull request
The following events has been tracked:

2021-12-20 22:04 UTC, fabriziofff requested changes
Could you also add the new events to https://docs.google.com/spreadsheets/d/1bXNRcTDKU-5l2RqCcwSbT7Y1M9QQTWtS_f-3-AIqSYk/edit#gid=0 ?

2021-12-21 09:19 UTC, debiff commented on ts/features/zendesk/analytics/index.ts
> +      case getType(getZendeskConfig.success):
Sure, modified in [2ed5c8f](https://github.com/pagopa/io-app/pull/3601/commits/2ed5c8f91e71588568e40a9635102a8f58e9067f)

2021-12-21 09:19 UTC, debiff commented on ts/features/zendesk/screens/ZendeskChooseCategory.tsx
> +    zendeskWorkUnitFailure("Config undefined");
Yes, thank you. Updated in [09f6a19](https://github.com/pagopa/io-app/pull/3601/commits/09f6a19be9e7ff9d74f93b5a181d7a1b60974146)

2021-12-21 09:21 UTC, debiff commented
> Could you also add the new events to https://docs.google.com/spreadsheets/d/1bXNRcTDKU-5l2RqCcwSbT7Y1M9QQTWtS_f-3-AIqSYk/edit#gid=0 ?

Sure! I was waiting for the legal approval, I'll add them right away!

2021-12-21 14:31 UTC, fabriziofff approved these changes

2021-12-21 14:31 UTC, merged