[IA-430] When the CIE PIN is wrong or the user goes back, the CIE PIN can't be set again
pagopa/io-app pull request #3632
Opened 2022-01-03 13:35 UTC by Undermaken

## Short description
This PR fixes a bug that doesn't allow the user to restart the CIE login flow.
It happens when the user is reading his/her card and the app goes back to the PIN insertion (automatically or by the user interaction)

### iOS before and after
https://pagopa.atlassian.net/browse/IA-430?focusedCommentId=28126

### Android before and after
https://pagopa.atlassian.net/browse/IA-430?focusedCommentId=28127

## How to test
- Start CIE login
- insert a wrong PIN
- scan your card
- tap on `Retry`
- try to insert the PIN again

2022-01-13 14:03 UTC, fabriziofff requested changes

2022-01-13 15:30 UTC, Undermaken commented on ts/screens/authentication/cie/CiePinScreen.tsx
> +  const handleAuthenticationOverlayOnClose = () => {
I missed it! ty
removed here https://github.com/pagopa/io-app/pull/3632/commits/3932a925e007d9178c95c2eff22421e227ecaa35

2022-01-13 17:48 UTC, fabriziofff commented on ts/screens/authentication/cie/CiePinScreen.tsx
> +  const handleAuthenticationOverlayOnClose = () => {
Now the same warning is shifted to `resetState`. One solution could be remove `resetState` and move the code in `handleAuthenticationOverlayOnClose`.

2022-01-13 19:08 UTC, Undermaken commented on ts/screens/authentication/cie/CiePinScreen.tsx
> +  const handleAuthenticationOverlayOnClose = () => {
😢  It's hard to see the yellow struggle, sorry
I hope now it's fine
https://github.com/pagopa/io-app/pull/3632/commits/e78381162287978195e1a770689507e63efbb86c

2022-01-14 11:05 UTC, fabriziofff approved these changes

2022-01-14 11:05 UTC, merged