[IAI-109] Added `redux-saga` effect types through `typed-redux-saga`
pagopa/io-app pull request #3730
Opened 2022-02-07 11:12 UTC by dgopsq

## Short description
This PR is going to add `typed-redux-saga` to the whole codebase.

## List of changes proposed in this pull request
- Integrated `typed-redux-saga`
- Integrated `typed-redux-saga` Babel macro to re-integrate `redux-saga` at compile time
- Integrated an ESLint rule to avoid `redux-saga/effects` import

## How to test
This refactor won't change the current application's behaviour.

2022-02-24 15:18 UTC, fabriziofff requested changes

2022-02-24 15:18 UTC, fabriziofff commented on ts/sagas/startup/watchLoadMessagesSaga.ts
> +          // Here we are not usint the `put` from typed-redux saga
```suggestion
          // Here we are not using the `put` from typed-redux saga
```

2022-02-24 15:18 UTC, fabriziofff commented on ts/sagas/startup/watchLoadMessagesSaga.ts
> +          // Here we are not usint the `put` from typed-redux saga
```suggestion
          // Here we are not using the `put` from typed-redux saga
```

2022-02-25 12:50 UTC, dgopsq commented on package.json
> +    "typed-redux-saga": "^1.3.1",
I missed that! It should be done in one of the latest commits :)

2022-02-25 12:51 UTC, dgopsq commented on .eslintrc.js
> +        "@jambit/typed-redux-saga/use-typed-effects": ["warn", "macro"],
Yep I agree, done!

2022-02-25 12:52 UTC, dgopsq commented on ts/sagas/startup.ts
> +      )) as unknown as SagaCallReturnType<
LGTM as a correction, I added it in the latest commits :)

2022-02-28 10:28 UTC, fabriziofff approved these changes

2022-02-28 10:28 UTC, merged