[IA-406] Fixed iOS accessibility "checked" translation
pagopa/io-app pull request #3791
Opened 2022-02-28 10:21 UTC by dgopsq

## Short description
This PR is going to patch the React Native NPM package, adding an Italian localisation file to translate the `checked` and `not checked` values.

The patch will just **add** a new file inside the React Native module, not changing anything else. The other english translations will be ported into the Italian translation and they will need to be translated in a future PR probably.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/5963683/155965869-80ab3249-103d-49fa-9f1d-41e37b216cbf.png">

## List of changes proposed in this pull request
- Translated the `checked` and `not checked` values in: `selezionato` and `non selezionato`

## How to test
Using the accessibility inspector to analyse the services configuration's radio buttons, while using iOS in Italian should result in having the `checked` and `not checked` values translated as `selezionato` and `non selezionato`.

2022-02-28 16:17 UTC, dgopsq commented
@thisisjp I added you as a reviewer too because there's translated text but not in the usual place (https://github.com/pagopa/io-app/pull/3791/files#diff-5f8f59afee259f80d174c30a791f101d87b9bc1086431df7a82e41345bde40a2R27-R28)

2022-02-28 16:31 UTC, thisisjp reviewed
@dgopsq I noticed there are other UI elements which required translation... I didn't go through all of them, but better than nothing, right? :)

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"toolbar"="tool bar";
```suggestion
+"toolbar"="barra degli strumenti";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"busy"="busy";
```suggestion
+"busy"="occupato";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"mixed"="mixed";
```suggestion
+"mixed"="misto";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"busy"="busy";
```suggestion
+"busy"="occupato";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"expanded"="expanded";
```suggestion
+"expanded"="espanso";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"collapsed"="collapsed";
```suggestion
+"collapsed"="compresso";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"checkbox"="checkbox";
```suggestion
+"checkbox"="casella di controllo";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"radio"="radio button";
```suggestion
+"radio"="pulsante di scelta";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"progressbar"="progress bar";
```suggestion
+"progressbar"="barra di avanzamento";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"scrollbar"="scroll bar";
```suggestion
+"scrollbar"="barra di scorrimento";
```

2022-02-28 16:31 UTC, thisisjp commented on patches/react-native+0.64.2.patch
> ++"menuitem"="menu item";
```suggestion
+"menuitem"="voce del menu";
```

2022-02-28 16:34 UTC, fabriziofff requested changes
Could you update the https://github.com/pagopa/io-app/blob/master/patches/patches.md#react-native0642 file, in order to track the reason of this patch?

2022-02-28 17:02 UTC, dgopsq commented
Thank you @thisisjp, I integrated everything 🙂 Also changed the PR title to a more generic one since we're going to address more translations than the ones in the ticket!

@fabriziofff I just added a small changelog, with a reference to this issue!

2022-03-02 10:17 UTC, fabriziofff approved these changes

2022-03-02 10:18 UTC, merged