[IA-668] Open the email client instead of the web form if the user denies submitting their information
pagopa/io-app pull request #3801
Opened 2022-03-03 10:38 UTC by debiff

## Short description
This PR aims to open the email client instead of the web form if the user denies submitting their information when opening a support ticket.

This PR also changes the screens' order in the Zendesk support workflow as a side effect.
Now, we first ask the user the ticket category then ask for permission to send the information.

## List of changes proposed in this pull request
- Added the `selectedSubcategory` reducer 
- Modified the order of the screens
- Open the predefined email client with the category (and eventually the subcategory) as subject

## How to test
The test suite was updated.
To test the email client opening you must use the physical device since there isn't an email client in the simulators.

2022-03-03 10:53 UTC, thisisjp commented
@debiff can we add a space between the ":" and the sub-category? 🤓

2022-03-07 17:02 UTC, Undermaken requested changes

2022-03-07 17:02 UTC, Undermaken commented on ts/features/zendesk/screens/ZendeskAskPermissions.tsx
> +    handleItemOnPress(
What about the error scenario? 
If the users have no email client set, should we show a message error?

https://user-images.githubusercontent.com/822471/157081720-e28ef126-5f75-41cb-97a2-8eeef0ffd067.mov

2022-03-08 15:28 UTC, debiff commented on ts/features/zendesk/components/ZendeskSupportComponent.tsx
> +      );
Thank you, refactored in [dbb4b77](https://github.com/pagopa/io-app/pull/3801/commits/dbb4b773f2f927360dc9c418b279bc5d6e14fa0f)

2022-03-08 15:28 UTC, debiff commented on ts/features/zendesk/screens/ZendeskAskPermissions.tsx
> +    )();
Yes, fixed in [181ae78](https://github.com/pagopa/io-app/pull/3801/commits/181ae78d102a180409013165b7a5638363a2ac3b)

2022-03-11 09:00 UTC, Undermaken approved these changes

2022-03-11 09:01 UTC, merged