Ia 729 loader and error handling
pagopa/io-app pull request #3853
Opened 2022-03-24 08:48 UTC by pietro909

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test

### In production
1. install the current release of the app
2. mark a few messages as _archived_ and open some of them to mark them _read_
3. note down the messages to compare them with the final result
4. install this branch on the device
5. on the first run, the migration starts
6. after a successful migration you shall see the new UI
7. check against the notes taken in (3) to verify that the process is working
8. no more migration must be done upon further reboots

### In dev

I suggest you update the dev-server to add some delay in the response and/or random errors to test for edge cases.

Add the snippet below in `ts/App.tsx` right before the `App` declaration:

```typescript
setTimeout(() => {
  const messages =
    store.getState().entities.messages.allPaginated.inbox.data.value?.page ||
    [];
  messages.forEach(message => {
    console.log(message.id);
    store.dispatch(DEPRECATED_setMessageReadState(message.id, true, "unknown"));
    store.dispatch(DEPRECATED_setMessagesArchivedState([message.id], true));
  });
}, 10000);
```

In `ts/screens/messages/paginated/MessagesHomeScreen.tsx` modify the condition on line 139 to always return `false`:

```typescript
const needsMigration = Object.keys(messagesStatus).length > 1000;
```

Open the app, log in, scroll down a few pages in the Inbox. After 10s the snippet above will mark all the messages it finds in Inbox as _read_ and _archived_. Take note of the IDs. 
Close the app, comment out the snippet, remove the patch of `needsMigration`, and start again the app.
Upon login, you should see the migration start and then finish.

The test in the video below was conducted locally with 68 messages and a 600ms delay per request. The Archived tab has much more pages than Inbox and many messages are marked as _read_ as a result of the migration described above.

https://user-images.githubusercontent.com/2094604/159877568-503af4b5-4a93-4d84-8e32-1a311e786399.mov

In the following recording, a failing message:

https://user-images.githubusercontent.com/2094604/159877780-12890f3b-9a84-4d65-b814-12c09cff5820.mov

2022-03-25 09:03 UTC, thisisjp commented
@pietro909 some minor fixes if possible:

1. The font used in the retry button is wrong
2. Can we use `pictograms/payment-completed.svg` for the happy case and `pictograms/doubt.svg` for the failure case?

2022-03-25 15:07 UTC, emiliopavia requested changes

2022-03-25 15:07 UTC, emiliopavia commented on ts/screens/messages/paginated/MigratingMessage.tsx
> +      setTimeout(onRetry, 2000);
Please can you explain this timeout? Thanks!

2022-03-28 13:18 UTC, pietro909 commented on ts/screens/messages/paginated/MigratingMessage.tsx
> +  onEnd: () => void;
Fixed [here](https://github.com/pagopa/io-app/pull/3853/commits/bb38a9404402fced607de1b5193023146163cb24#diff-ced3d0535c496b8124b980c773e751099334a086e942481b881083794bdd34f4L44)

2022-03-28 13:19 UTC, pietro909 commented on locales/it/index.yml
> +      failed: "Non siamo riusciti ad aggiornare la pagina dei messaggi a causa di un errore. Premi il bottone per riprovare"
@thisisjp is working on this.

2022-03-28 15:53 UTC, emiliopavia approved these changes
In my tests it seems to work as described.

2022-03-28 15:59 UTC, merged