[IABT-1364] Add accessibility fixes to the checkout page
pagopa/io-app pull request #3869
Opened 2022-03-31 09:14 UTC by dgopsq

## Short description
This PR is going to fix two accessibility issues in the checkout page.

<details>
<summary>Payment method preview</summary>
<img width="1414" alt="Screenshot 2022-03-31 at 11 10 25" src="https://user-images.githubusercontent.com/5963683/161020658-06e03e7f-b9e6-4a3a-ad38-632b549fdfec.png">
<img width="1416" alt="Screenshot 2022-03-31 at 11 11 25" src="https://user-images.githubusercontent.com/5963683/161020648-f6e72c62-c92b-4fa8-98d2-c3a657be74ef.png">
</details>

<details>
<summary>PSP preview</summary>
<img width="1425" alt="Screenshot 2022-03-31 at 11 12 10" src="https://user-images.githubusercontent.com/5963683/161020633-12958269-a6d8-4943-9ad9-a8b1ae7efee3.png">
</details>

## List of changes proposed in this pull request
- Added the second line of informations to the accessibility label of each payment method
- Fixed a typo in the PSP accessibility label

## How to test
Using the accessibility inspector in the checkout page:
- The payment method box should read the second line of informations too (name, surname and expiration date for a generic payment method)
- The PSP box should not read "Provided by" two times

2022-03-31 12:54 UTC, thisisjp commented on locales/it/index.yml
> +      transactionCosts: "{{cost}}, {{psp}}"
@dgopsq I think the issue is that the string "psp" contains the words "Gestita da", that's why the VoiceOver reads "transazione gestita da gestita da".

2022-03-31 12:55 UTC, thisisjp commented on locales/it/index.yml
> +      transactionCosts: "{{cost}}, {{psp}}"
```suggestion
      transactionCosts: "{{cost}}, transazione {{psp}}"
```

2022-03-31 12:56 UTC, thisisjp requested changes
Check my inline comments

2022-03-31 13:05 UTC, thisisjp approved these changes

2022-04-06 16:52 UTC, Undermaken approved these changes

2022-04-06 17:07 UTC, Undermaken approved these changes

2022-04-06 17:10 UTC, merged