[AP-37] Update outcome message on CDC partially success screen
pagopa/io-app pull request #3985
Opened 2022-05-27 13:56 UTC by debiff

## Short description
This PR updates the outcome message on `CdcRequestPartiallySuccess` as proposed in the UI.
For every kind of error now there is a specific message.

## List of changes proposed in this pull request
- Refactored the `CdcRequestPartiallySuccess` adding a specific message for every error type
<img src="https://user-images.githubusercontent.com/11773070/170713464-83a9c630-a2f9-4244-9aad-3cbc6046b348.png" width=300>

## How to test
The test suite is provided.
Activate both the remote feature flag and the bonus in the dev server and try to return the different combinations.

2022-06-03 13:42 UTC, dgopsq requested changes

2022-06-06 15:32 UTC, debiff commented on ts/features/bonus/cdc/components/__test__/CdcRequestPartiallySuccess.test.ts
> +    outcome: RequestOutcomeEnum.INIZIATIVA_TERMINATA
Sure! Added in [78a7f9d](https://github.com/pagopa/io-app/pull/3985/commits/78a7f9d1317412bf747b3fc6f387e920d1d5f0e4)

2022-06-10 11:58 UTC, dgopsq approved these changes

2022-06-10 12:00 UTC, dgopsq commented
@thisisjp If this is ok for you I'm going to merge it 🙂

2022-06-10 12:08 UTC, thisisjp commented
@Loreau says ok :)

2022-06-10 13:06 UTC, merged