[IAI-192] Upgrade `react-native` to `0.69.4`
pagopa/io-app pull request #4103
Opened 2022-08-12 14:48 UTC by CrisTofani

## Short description
This PR aims to upgrade react-native to the latest stable version.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2022-09-08 12:46 UTC, emiliopavia approved these changes
I haven't noticed any regressions on my tests. The only thing to fix is the Podfile that is out of sync after running `pod install`.

2022-10-20 07:21 UTC, francescopersico requested changes

2022-10-20 07:21 UTC, francescopersico commented on android/gradle.properties
> +#android.enableR8=false
We can safely remove this

2022-10-20 07:21 UTC, francescopersico commented on android/gradle.properties
>  org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
Remove this, we are already setting the jvmargs we need on line 13.

2022-10-20 07:21 UTC, francescopersico commented on android/gradle.properties
> +# Use this property to enable support to the new architecture.
```suggestion

# Use this property to enable support to the new architecture.
```

2022-10-20 07:21 UTC, francescopersico commented on android/gradle.properties
> +newArchEnabled=false
```suggestion
newArchEnabled=false

```

2022-10-24 10:34 UTC, francescopersico approved these changes

2022-10-24 11:08 UTC, merged