[IOAPPFD0-10] Startup saga, onboarding refactoring
pagopa/io-app pull request #4168
Opened 2022-11-10 11:23 UTC by Vangaorth

# ⚠️ This pr depends on #4147 ⚠️
Please review #4147 first in order to avoid duplicate review work.

## Short description
This PR refactors the onboarding branching on the startup saga, in order to have a cleaner code

## List of changes proposed in this pull request
This PR aims to simplify the startup saga by re-arranging the onboarding branch condition.

The current state of the code is shown in the following diagram

![00](https://user-images.githubusercontent.com/5150343/201076724-fb3652f4-19ef-4521-ae54-d85cda76091f.png)

The simplification process focuses on removing the direct flow on the right side of the diagram, which skips all the intermediate calls.

That condition happens when these three conditions are all met: there is a previous session token, there is a local stored pin and the session was refreshed. Specifically, we focus on the last of the three conditions (i.e., the session was refreshed).
If it is met, then the `previousSessionToken` must be different from the `sessionToken`. This happens only if the `previousSessionToken` value is `falsy` (otherwise, the two tokens will have the same value and the condition is not met). Now, having a `falsy` `previousSessionToken` means that the branch containing the condition is not even executed, since the first of the initial three conditions (i.e., there is a previous session token) is not met anymore.

With the consideration above, we deduct that the flow is never executed and can be safely removed, leading to the following simplified diagram

![01](https://user-images.githubusercontent.com/5150343/201076768-2e8c7caf-7cef-427b-a9c6-0aceeea9d5e0.png)

From this, we can see that there are some common steps, executed on both branches. Our proposal is to completely remove the branching and execute the steps using guards that maps the branching condition, formally:

- current execution has both session and pin;
- current execution has no session or no pin (which is the logical negation of the previous)

Other conditions are mapped adding additional guards to either one or the other.

This last diagram is the final code refactoring that is being proposed with this PR:

![02](https://user-images.githubusercontent.com/5150343/201076803-0062b7f7-9511-4cd7-bf31-f564c6658d93.png)

Note that we need to compute the `isFirstOnboarding` parameter before `call(askServicesPreferencesModeOptin(isFirstOnboarding: boolean))`.

Also note that, the flow condition `(has no session OR has no pin) AND isFirstOnboarding` can be further simplified to just check `isFirstOnboarding`, since if the user does not have a session, the code flow is interrupted long before reaching this point and the same goes for the not having a pin.

## How to test
In order to test this PR you have to go through the onboarding process so start an instance of the io-app-dev-server with the `firstOnboarding` set to `true` and make sure to reinstall the application (i.e., no previously saved local data on the device/simulator). In this case, you should see all the onboarding screens (namely, ToS, Mixpanel OptIn, Pin Configuration, Fingerprint (on device), email ACK, push notifications OptIn, service configuration and onboarding completion).

After this, you can test again, by restarting the io-app-dev-server with the `firstOnboarding` flag set to `false` (do not reinstall the application). In this case, you should only see the PIN screen and the push notification OptIn.

Also check all the logout/reset features during the PIN verification and during the onboarding.

2022-11-21 14:38 UTC, francescopersico requested changes

2022-11-22 13:11 UTC, Vangaorth commented on ts/components/ui/BlockButtons.tsx
> +export interface TwoButtonsVertical extends CommonProps {
Bad code from a previous PR. Removed

2022-11-22 13:21 UTC, Vangaorth commented on ts/sagas/startup.ts
> +  // This block has been refactored to avoid a code duplication on an if-else branching.
Comments updated

2022-12-06 10:00 UTC, CrisTofani requested changes

2022-12-06 10:00 UTC, CrisTofani commented on ts/sagas/startup.ts
> +  }
Could this block of code be moved inside the `if` clause at line [321](https://github.com/pagopa/io-app/pull/4168/files#diff-8a5b2f3967d681b976fe673762bd1061f5b430130c880c1195b76af06362cf31R321)?

2022-12-06 11:43 UTC, CrisTofani approved these changes
LGTM @shadowsheep1 @francescopersico  waiting your approval to merge

2022-12-14 09:55 UTC, shadowsheep1 approved these changes

2022-12-20 17:08 UTC, Vangaorth commented on ts/sagas/startup.ts
> +  if (hasPreviousSessionAndPin) {
That's due to the scope of this PR, which was to simplify a branching condition with duplicate code. Removing the check for the session may be possible but it is out of the PR scope (here's the tracking https://pagopa.atlassian.net/browse/IOAPPCIT-10)

2022-12-20 17:13 UTC, francescopersico approved these changes

2022-12-21 07:58 UTC, merged