[IODPAY-45] Added BonusCardScreen
pagopa/io-app pull request #4192
Opened 2022-11-22 16:31 UTC by forrest57

## Short description
Added a BonusDetails screen, along with its new required card component and included it in the AppStackNavigator.
<img width="200" alt="Screenshot 2022-11-22 at 17 21 33" src="https://user-images.githubusercontent.com/60693085/203366926-1e332fa4-2719-4b1c-8081-b456bd36ea8b.png">

## List of changes proposed in this pull request
- Implementation of the BonusDetailsScreen page.
- Addition of said page to the AppStackNavigator in order to be able to start the IDPAY workflow from anywhere in the app. 
- Introduction of the new BonusCardComponent, a refactor of BonusVacanze's card component which uses an SVG as background and flex values instead of hardcoded ones to accomodate the new data display requirements.
- both the page and the component display conditional data as per design.

## How to test
from anywhere in the app, navigate to ROUTES.BONUS_DETAILS with params {initiativeId:string}, and the page will display, also logging the passed initiativeID.

2022-11-22 16:37 UTC, forrest57 commented on ts/navigation/params/AppParamsList.ts
> -import UADONATION_ROUTES from "../../features/uaDonations/navigation/routes";
import sorting, nothing was actually deleted

2022-11-22 17:16 UTC, francescopersico requested changes

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/components/BonusCardComponent.tsx
> +const BonusCardComponent = (props: Props) => {
```suggestion
const InitiativeCardComponent = (props: Props) => {
```

please also use the term Initaitive in the rest of the code.

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/components/BonusCardComponent.tsx
> +    const isBonusActive = props.status === StatusEnum.REFUNDABLE;
```suggestion
    const isInitiativeConfigured = props.status === StatusEnum.REFUNDABLE;
```

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/components/BonusCardComponent.tsx
> +                {`${props.amount},00 €`}
Use the proper amount formatter function.

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/components/BonusCardComponent.tsx
> +            <Image source={bonusVacanzeWhiteLogo} style={styles.logo} />
Why bonus vancaze?

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/screens/BonusDetailsScreen.tsx
> +const BonusDetailsList = (bonus: InitiativeDTO) => (
Why not a component?

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/screens/BonusDetailsScreen.tsx
> +const BonusDetailsList = (bonus: InitiativeDTO) => (
Also why BonusDetailsList? This component is not a List of BonusDetail.

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/screens/BonusDetailsScreen.tsx
> +  const bonus: InitiativeDTO = {
Why you need this **inside** the component?

2022-11-22 17:16 UTC, francescopersico commented on ts/features/idpay/initiative/details/screens/BonusDetailsScreen.tsx
> +            BonusDetailsList(bonus)
Read above.

2022-11-25 10:49 UTC, mastro993 requested changes

2022-11-25 10:49 UTC, mastro993 commented on ts/features/idpay/initiative/details/saga/__test__/handleGetInitiativeDetails.test.ts
> +  });
Left is called only when there is an API exception. An API error (status code != 200) is usually a Right with an ErrorDTO object inside.

2022-11-25 14:34 UTC, merged