[IAI-264] Remove NativeBase's `View` component
pagopa/io-app pull request #4306
Opened 2023-01-18 13:55 UTC by dmnplb

### ⚠️ This PR depends on #4302  

## Short description
This PR removes all instances of the NativeBase `View' component and replaces them with the React Native one.

## List of changes proposed in this pull request
- Remove classes of the NativeBase `View` component, replacing with new styles defined in the `IOStyles` object
- Replace all the legacy instances with the native `View` component

2023-01-31 10:00 UTC, hevelius reviewed
This is mainly a replacement of View component from `native-base` to `react-native`. I tried this branch on the iOS simulator and found no problems (not tested on Android). LGTM but  parts of IO are altered that I have no context about so I can give only a general feedback.

2023-01-31 12:15 UTC, hevelius commented
@dmnplb I tried some paths and I noticed this problem on the color of the button text.

![Simulator Screen Shot - iPhone 6s - 2023-01-31 at 13 05 32](https://user-images.githubusercontent.com/49342144/215756431-77aa9d7d-9809-4d42-ad30-7dfeb8cb3d3c.png)

2023-01-31 13:12 UTC, dmnplb commented
> @dmnplb I tried some paths and I noticed this problem on the color of the button text.

There's a visual bug triggered by the lack of `labelColor` prop in some configurations of `BlockButtons`. Thanks for the report.

2023-02-23 14:50 UTC, CrisTofani reviewed
it looks like there's some extra space in the messages with CTA

[Testflight]
<img height="300" src="https://user-images.githubusercontent.com/3959405/220940741-681d3140-9090-4dcb-9c27-382a9c01c9c0.png" />

[This PR]
<img height="300" src="https://user-images.githubusercontent.com/3959405/220940794-84576031-9f8c-401e-9531-e37be8b6d9ea.png" />

2023-02-23 14:53 UTC, CrisTofani commented
> it looks like there's some extra space in the messages with CTA
> 
> [Testflight] <img alt="" height="300" src="https://user-images.githubusercontent.com/3959405/220940741-681d3140-9090-4dcb-9c27-382a9c01c9c0.png">
> 
> [This PR] <img alt="" height="300" src="https://user-images.githubusercontent.com/3959405/220940794-84576031-9f8c-401e-9531-e37be8b6d9ea.png">

<img alt="" height="300" src="https://user-images.githubusercontent.com/3959405/220941873-8c97c445-6287-43bc-a80c-406481d962d1.png">

It looks like the extra space is part of the message detail/safe area visualization

2023-03-07 15:53 UTC, mastro993 commented
<img src="https://user-images.githubusercontent.com/6160324/223474663-8e4e26f2-5ef6-4c0f-9ac6-d968a50cf808.png" width="200" />

Buttons created with `FooterWithButtons`. Default label color should change based on `bordered` prop.
In this case we have:

```
<FooterWithButtons
      type="TwoButtonsInlineThird"
      rightButton={{
        onPress: handleEnrollConfirm,
        block: true,
        bordered: false,
        labelColor: IOColors.white,
        title: I18n.t(
          "idpay.configuration.instruments.enrollmentSheet.buttons.activate"
        )
      }}
      leftButton={{
        onPress: () => {
          enrollmentBottomSheetModal.dismiss();
        },
        block: true,
        bordered: true,
        title: I18n.t(
          "idpay.configuration.instruments.enrollmentSheet.buttons.cancel"
        )
      }}
    />
    ```

2023-03-09 08:32 UTC, Vangaorth commented on ts/components/screens/BaseHeader.tsx
> +  private firstElementRef = React.createRef<any>(); // Could be NBText or View
Can we use `<NBText | View>` instead of any and explicitly cast it later as
`ref={this.firstElementRef as React.RefObject<View>}`
?

2023-03-09 09:34 UTC, Vangaorth commented
On messages with payment notice, there is not enough space between the end of message content and the bottom footer

[TestFlight / Production]
![Screenshot 2023-03-09 at 10 22 44](https://user-images.githubusercontent.com/5150343/223979699-bd8bd2d6-3e53-4de4-bd5d-5e7bc4fd9a62.png)

[This PR]
![Screenshot 2023-03-09 at 10 07 00](https://user-images.githubusercontent.com/5150343/223979748-b27eb0e2-8703-45a6-93d3-7d54882144a9.png)

2023-03-10 15:51 UTC, dmnplb commented
> On messages with payment notice, there is not enough space between the end of message content and the bottom footer

@Vangaorth Solved these visual inconsistencies replacing `Content` (a NativeBase component) with the native `ScrollView` from `react-native` in the `MessageDetail` screen

2023-03-15 08:11 UTC, Vangaorth approved these changes
LGTM after the last few changes! Outstanding work 🔝

2023-03-15 09:19 UTC, CrisTofani approved these changes
LGTM

2023-03-15 10:08 UTC, mastro993 commented
> <img alt="" width="200" src="https://user-images.githubusercontent.com/6160324/223474663-8e4e26f2-5ef6-4c0f-9ac6-d968a50cf808.png">
> 
> Buttons created with `FooterWithButtons`. Default label color should change based on `bordered` prop. In this case we have:
> 
> ```
> <FooterWithButtons
>       type="TwoButtonsInlineThird"
>       rightButton={{
>         onPress: handleEnrollConfirm,
>         block: true,
>         bordered: false,
>         labelColor: IOColors.white,
>         title: I18n.t(
>           "idpay.configuration.instruments.enrollmentSheet.buttons.activate"
>         )
>       }}
>       leftButton={{
>         onPress: () => {
>           enrollmentBottomSheetModal.dismiss();
>         },
>         block: true,
>         bordered: true,
>         title: I18n.t(
>           "idpay.configuration.instruments.enrollmentSheet.buttons.cancel"
>         )
>       }}
>     />
> ```

After some more investigations we discovered that the problem is related to the `useIOBottomSheetModal`: when a button is placed inside a `BottomSheetModal` the default label color for the solid button is blue instead of white.

2023-03-15 10:10 UTC, mastro993 requested changes
> <img alt="" width="200" src="https://user-images.githubusercontent.com/6160324/223474663-8e4e26f2-5ef6-4c0f-9ac6-d968a50cf808.png">
> 
> Buttons created with `FooterWithButtons`. Default label color should change based on `bordered` prop. In this case we have:
> 
> ```
> <FooterWithButtons
>       type="TwoButtonsInlineThird"
>       rightButton={{
>         onPress: handleEnrollConfirm,
>         block: true,
>         bordered: false,
>         labelColor: IOColors.white,
>         title: I18n.t(
>           "idpay.configuration.instruments.enrollmentSheet.buttons.activate"
>         )
>       }}
>       leftButton={{
>         onPress: () => {
>           enrollmentBottomSheetModal.dismiss();
>         },
>         block: true,
>         bordered: true,
>         title: I18n.t(
>           "idpay.configuration.instruments.enrollmentSheet.buttons.cancel"
>         )
>       }}
>     />
> ```

After some more investigations we discovered that the problem is related to the `useIOBottomSheetModal`: when a button is placed inside a `BottomSheetModal` the default label color for the solid button is blue instead of white.

2023-03-15 17:08 UTC, mastro993 approved these changes

2023-03-20 10:55 UTC, merged