chore(Firma con IO): [SFEQS-1402] Generic error component refactoring with locale updates
pagopa/io-app pull request #4389
Opened 2023-02-16 15:42 UTC by hevelius

## Short description
This PR changes the generic error component by adding the retry prop and all locales for each error scenario.

## List of changes proposed in this pull request
- Update `GenericErrorComponent`
- Update all screens that make use of it
- Update related test

## How to test

2023-03-16 09:48 UTC, hevelius commented on ts/features/fci/components/SuccessComponent.tsx
> +    createSelector(lollipopPublicKeySelector, V => V)
@shadowsheep1 what do you think about this temp solution?

2023-03-24 11:38 UTC, shadowsheep1 requested changes

2023-03-24 11:38 UTC, shadowsheep1 commented on ts/features/fci/components/ErrorComponent.tsx
> +  };
What do you think writing something like that?

 ```ts
const buttonProps = {
    block: true,
    primary: true,
    onPress: props.onPress
  };

  const closeButtonProps = {
    ...buttonProps,
    bordered: true,
    title: I18n.t("global.buttons.close")
  };

  const retryButtonProps = {
    ...buttonProps,
    title: I18n.t("global.buttons.retry")
  };
```
We could improve code readability by separating between "standard" props and the one specific for "close" or "retry" buttons.

2023-03-24 11:38 UTC, shadowsheep1 commented on ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
> +    />
Ain't this case covered at lines 60-70?

2023-03-24 14:18 UTC, hevelius commented on ts/features/fci/screens/valid/FciDocumentPreviewScreen.tsx
> +    />
Good catch!

2023-03-24 15:46 UTC, shadowsheep1 approved these changes
LGTM

2023-03-24 15:47 UTC, merged