chore(Firma con IO): [SFEQS-1608] Update locales for clauses type
pagopa/io-app pull request #4543
Opened 2023-04-14 13:43 UTC by hevelius

## Short description
This PR updates the locales string related to clauses type.

## List of changes proposed in this pull request
- Update locales
- Update signatureFields util
- Update test

## How to test
Test should solve correctly. Using io-dev-server on the FciSginatureFieldsScreen the section header should render correctly.

2023-04-14 13:59 UTC, hevelius commented on locales/en/index.yml
> +      unfair: "UNFAIRES SIGNATURES"
@AliceAzzolini

2023-04-14 13:59 UTC, hevelius commented on locales/it/index.yml
> +      unfair: "FIRME CLAUSOLE VESSATORIE"
@AliceAzzolini

2023-04-14 14:40 UTC, AliceAzzolini approved these changes

2023-04-17 12:45 UTC, CrisTofani requested changes

2023-04-17 12:45 UTC, CrisTofani commented on ts/features/fci/utils/signatureFields.ts
> +};
if we use this approach the app may fail translating this labels at run time, there are 2 possibilities:
- use a function to return the correct value
- map the TranslationKeys in the object and not the locale label itself

what do you think?

2023-04-17 13:36 UTC, CrisTofani approved these changes

2023-04-17 13:42 UTC, merged