feat(IT Wallet): [SIW-182] Update app icon
pagopa/io-app pull request #4714
Opened 2023-06-27 16:49 UTC by hevelius

## Short description
This PR update the app icon for iOS and Android

## How to test
Running on simulator or device the App Icon should change

2023-06-29 13:17 UTC, LazyAfternoons requested changes
There's something wrong with this PR as it includes some, I guess, unwanted changes. For example, the `Gemfile.lock` has been changed by this PR even though it's not included in the `Files changed` section.
Running the app gives error because the Cocoapods version has been updated and it doesn't match the one in the bundle/it-wallet branch.
It also shouldn't have 22 commits.

2023-06-29 13:21 UTC, hevelius commented
> There's something wrong with this PR as it includes some, I guess, unwanted changes. For example, the `Gemfile.lock` has been changed by this PR even though it's not included in the `Files changed` section.
> 
> Running the app gives error because the Cocoapods version has been updated and it doesn't match the one in the bundle/it-wallet branch.
> 
> It also has 22 commits.

You're right! Using last Xcode version sonethings changes. I'll be right to fix. Thanks.

2023-07-01 12:40 UTC, LazyAfternoons approved these changes

2023-07-01 12:41 UTC, LazyAfternoons commented
LGTM, tested on both Android and iOS.

2023-07-01 15:38 UTC, merged