[IOPID-359] First onboarding refactor
pagopa/io-app pull request #4720
Opened 2023-06-28 13:49 UTC by SabPicariello

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- ts/i18n.ts: since the English language has all the keys of the Italian language, it is the new fallback. New users who enter the app with devices with a language other than English/Italian/German will have English instead of Italian.
- ts/sagas/profile.ts: last_app_version and preferred_languages are always set if not found at every profile upsert. Upsert and checks on the profile are prevented until acceptance of the tos which becomes the first upsert of the app (during this first upsert it also sets the app version and language). This way there are also no more upsert and duplicate checks when creating a new profile.
- ts/store/reducers/profile.ts: Having profile version 0 is not enough to tell if you are an onboarding. The check is now done on service_preferences_settings which is set to legacy until the last onboarding screen.
- *.test.ts: updates

## How to test
Run dev server with first onboarding set to true and make sure that all the described behaviors are respected.

2023-06-28 14:21 UTC, thisisjp commented
@SabPicariello 
>since the English language has all the keys of the Italian language

this is not true: content designers always provide the Italian localization. We're planning to better structure the localization workflow, but in any case the translated strings will arrive t+1.

cc @AliceAzzolini

2023-06-28 14:34 UTC, SabPicariello commented
> 



> @SabPicariello
> 
> > since the English language has all the keys of the Italian language
> 
> this is not true: content designers always provide the Italian localization. We're planning to better structure the localization workflow, but in any case the translated strings will arrive t+1.
> 
> cc @AliceAzzolini

I am aware of it. I meant that any key present in the Italian file, is also present in the English file (although in this one we sometimes find values associated with keys, in Italian language). This allows us to move the fallback language (in case the user has, for example, the device in French) from Italian to English, without creating errors. 
The fact that the user will see some sentences in Italian is certain, but a few sentences are always better than the whole application. Do you agree?

2023-06-30 13:38 UTC, shadowsheep1 requested changes
Just a minor change.

2023-06-30 13:38 UTC, shadowsheep1 commented on ts/sagas/profile.ts
> +  );
```suggestion
const appVersion = pipe(
    rawAppVersion,
    AppVersion.decode,
    E.fold(
      () => undefined,
      version => version
    )
  );
```
What do you think of this version?

2023-06-30 14:12 UTC, shadowsheep1 approved these changes
LGTM

2023-06-30 14:52 UTC, merged