[IOBP-170] Add multiple pagoPA barcode choice screen
pagopa/io-app pull request #4915
Opened 2023-08-10 13:48 UTC by mastro993

## ⚠️ Depends on https://github.com/pagopa/io-app/pull/4771, https://github.com/pagopa/io-app/pull/4905

## Short description
This PR adds the screen which allow to choose from multiple decoded pagoPA barcodes

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
With the `io-dev-server`, try to scan a document with multiple pagoPA barcodes.

2023-08-30 13:40 UTC, Hantex9 requested changes
There is a strange behavior when I upload a file with more than one valid pagoPA qr code.

I uploaded a file with 2 valid pagoPA codes and it navigates correctly to the choosing screen but inside the list is rendered the same amount and code of the last qrcode repeated twice.

I try to attach a screenshot, the code and details are omitted but I can assure you that they are the same (look at the amount) even if a notice is of 141,87€ and the other 102,43€

<img src="https://github.com/pagopa/io-app/assets/34343582/f9c3030b-e281-4c84-89cd-c9c163ca770e" width="250" />

2023-08-30 14:11 UTC, mastro993 commented on ts/features/walletV3/payment/components/PaymentNoticeListItem.tsx
> +      <H6 color="blueIO-450">{amountString}</H6>
Fixed in https://github.com/pagopa/io-app/pull/4915/commits/51edd07e7886e32089601e619258b34dbed5c0f0

2023-08-31 08:02 UTC, mastro993 commented
> a36bc67

Fixed in https://github.com/pagopa/io-app/pull/4915/commits/a36bc677ce40fb0f74e3668b36e6d55fecb58712

2023-08-31 08:02 UTC, mastro993 commented
> There is a strange behavior when I upload a file with more than one valid pagoPA qr code.
> 
> I uploaded a file with 2 valid pagoPA codes and it navigates correctly to the choosing screen but inside the list is rendered the same amount and code of the last qrcode repeated twice.
> 
> I try to attach a screenshot, the code and details are omitted but I can assure you that they are the same (look at the amount) even if a notice is of 141,87€ and the other 102,43€
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/34343582/264348815-f9c3030b-e281-4c84-89cd-c9c163ca770e.png">

Fixed in https://github.com/pagopa/io-app/pull/4915/commits/a36bc677ce40fb0f74e3668b36e6d55fecb58712

2023-08-31 09:02 UTC, Hantex9 approved these changes
LGTM! 👏

2023-10-11 18:39 UTC, merged