[IOPID-666] FL missing pin logout flow
pagopa/io-app pull request #4968
Opened 2023-09-12 09:08 UTC by sabontech

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-09-13 08:49 UTC, shadowsheep1 requested changes
In a clean device all works fine! 🚀. But I guess there is a critical path with our cross session management.

| Cross Session in Action? | Clean Device |
| - | - |
| <video src="https://github.com/pagopa/io-app/assets/16268789/195dbedd-047b-40f3-8dcc-591dfcf3198f" /> | <video src="https://github.com/pagopa/io-app/assets/16268789/9b90f0df-fa35-4ec6-8e32-b6b3791e7b8e" /> |

2023-09-14 08:58 UTC, sabontech commented
> In a clean device all works fine! 🚀. But I guess there is a critical path with our cross session management.
> 
> Cross Session in Action?	Clean Device
>  cross-session-edge-case.mp4 
>  clean-patch.mp4

We could move the cross session check right after login, before tos acceptance, to allow it to delete the pin stored in keychain in iOS. This check doesn't send data to backend. What do you think?
I already implemented this solution in my last commit if you want to try.

2023-09-14 09:13 UTC, AliceAzzolini approved these changes

2023-09-14 09:13 UTC, AliceAzzolini commented on locales/en/index.yml
> +        title: È passato troppo tempo!
```suggestion
        title: Too much time has passed!
```

2023-09-14 09:13 UTC, AliceAzzolini commented on locales/en/index.yml
> +        subtitle: Per ragioni di sicurezza devi autenticarti di nuovo con SPID o CIE. Potrai poi continuare la configurazione di IO da dove l’avevi interrotta.
```suggestion
        subtitle: For security reasons, you must authenticate again with SPID or CIE. You can then resume IO configuration from where you left off.
```

2023-09-14 09:13 UTC, AliceAzzolini commented on locales/en/index.yml
> +        submitButtonTitle: Continua
```suggestion
        submitButtonTitle: Continue
```

2023-09-14 14:30 UTC, shadowsheep1 approved these changes
LGTM

2023-09-15 08:36 UTC, merged