[SIW-362] Adds a component to parse a markdown string and get a collection of ReactNode elements
pagopa/io-app pull request #4969
Opened 2023-09-12 12:42 UTC by hevelius

## Short description
This PR adds a new `ItwTextInfo` component that given a string of markdown text returns a set of ReactNode items using e regex expression. This component supports only regular text, bolded text (**) and link.

## How to test
Import this component in any of available screens passing ad text a markdown string ex.

`const markdownText = "Lorem ipsum dolor sit amet, **consectetur adipiscing elit**. Quisque tortor libero, **facilisis** non lectus eget, scelerisque finibus urna. [Nullam volutpat]() enim enim, sed pulvinar dolor mollis et."`

2023-10-11 13:37 UTC, dmnplb commented
Hi @hevelius,
Can we use this component to format rich text in the various components that accept `ReactNode` as input? If so, it might be useful to use it throughout the application.

2023-10-11 14:32 UTC, hevelius commented
> Hi @hevelius, Can we use this component to format rich text in the various components that accept `ReactNode` as input? If so, it might be useful to use it throughout the application.

Hi @dmnplb! This component was born precisely as a need in `it-wallet` to be able to efficiently manage texts that require inline formatting. However the nature of this component is still experimental. For now we would like to try it first in the context of `it-wallet`. However, the idea is to be able to use it later throughout the application. Please if you want to try this component. Please, if you want to try this component, it would be great to have your opinion!

2023-10-16 13:31 UTC, LazyAfternoons requested changes

2023-10-16 13:31 UTC, LazyAfternoons commented on ts/features/it-wallet/components/ItwTextInfo.tsx
> +import { showToast } from "../../../utils/showToast";
We can replace this legacy `showToast` utility with a toast from the new DS.

2023-10-19 08:29 UTC, LazyAfternoons approved these changes
LGTM

2023-10-19 11:26 UTC, merged