[IOBP-238] IDPAY CODE onboarding flow Xstate and flow basics
pagopa/io-app pull request #4976
Opened 2023-09-13 10:31 UTC by forrest57

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-09-15 07:10 UTC, Hantex9 approved these changes
Since it's a boilerplate to build other features, LGTM!

2023-09-18 07:11 UTC, mastro993 requested changes
Will `code` feature need other sub-features? Maybe `ts/features/idpay/code/onboarding` would be better

2023-09-18 07:19 UTC, mastro993 requested changes

2023-09-18 07:19 UTC, mastro993 commented on ts/features/idpay/codeOnboarding/xstate/machine.ts
> +        SHOWING_PIN: {
```suggestion
        DISPLAYING_PIN: {
```

2023-09-25 14:52 UTC, mastro993 commented
Switched to Redux-Saga https://github.com/pagopa/io-app/pull/4995

2023-09-25 14:52 UTC, closed without merging