[IABT-1493] Apply patch to fix camera crash on iPhone 15
pagopa/io-app pull request #5049
Opened 2023-09-29 12:39 UTC by hevelius

## Short description
This PR adds apply a patch to react-native-vision-camera that resolve a crash on IPhone 15 device.

## How to test
Build the app and start the QR code screen. Try to scan a QR Code and everything should work as expected.

2023-09-29 16:08 UTC, mastro993 approved these changes
Tested on **iPhone 13 Mini** with **iOS 16.5**.
Everything works as expected!

2023-09-29 17:57 UTC, shadowsheep1 requested changes
I would consider to update [`patches.md`](https://github.com/pagopa/io-app/blob/master/patches/patches.md) file, by adding the contextual info about those additions to the patch.

2023-10-02 08:32 UTC, shadowsheep1 requested changes

2023-10-02 08:32 UTC, shadowsheep1 commented on patches/patches.md
> +- This patch going to remove all codes related to `colorSpace` to fix an issue on iOS 17.0.2 that cause the crash on camera load
The have fixed in the v2 branch [here](https://github.com/mrousavy/react-native-vision-camera/issues/1840#issuecomment-1741734963). If they'll release `2.16.2` we could remove this patch at all. We want to add evidence of this? What do you think?

2023-10-02 13:23 UTC, shadowsheep1 approved these changes
LGTM

2023-10-03 13:27 UTC, merged