[IOPLT-184] Base Screen component wrapper header with animated title
pagopa/io-app pull request #5088
Opened 2023-10-10 09:14 UTC by CrisTofani

## Short description
This PR implements a base wrapper component for a Screen that needs to handle the Title both as part of the screen content and as dissolving navigation header attribute.

## List of changes proposed in this pull request
- Created `ScrollableScreenContent`
- Changed the old Screen in the DS section

## How to test
Check the DS section

⚠️ This PR depends on #5028

2023-10-10 13:09 UTC, dmnplb requested changes

2023-10-10 13:27 UTC, CrisTofani commented on ts/components/ui/ScrollableScreenContent.tsx
> +export const ScrollableScreenContent = ({
thx naming is not my strongest skill 👀

2023-10-11 07:35 UTC, dmnplb approved these changes

2023-11-23 15:03 UTC, hevelius approved these changes
LGTM. It works as expected.

2023-11-23 15:23 UTC, merged