[IOPID-938] opt-in screen
pagopa/io-app pull request #5096
Opened 2023-10-11 09:03 UTC by Ladirico

## Short description
By implementing the Fast Login there is a need to make the user choose whether to use the standard login or to use the Quick Login. I implemented this screen by referring to [this mockup ](https://www.figma.com/file/BEXvjQmBkMRRFiNcMgE8g3/Login-Veloce?type=design&node-id=2843-27901&mode=design&t=1rt63XBjxBPMAyTB-0)

## List of changes 
proposed in this pull request
- Screen realization NewOptInScreen.tsx
- Test screen NewOptInScreen.test.tsx
- Insertion of navigation logic in the **LandingScreen.tsx**
- Integration of business logic 

https://github.com/pagopa/io-app/assets/83651704/4d0101ae-d3fc-499e-858e-531726f34869

## How to test
In **.env file** FAST_LOGIN_ENABLED=YES 
in io-dev-server-api config.ts firstOnboarding:true
Run the application

2023-10-12 10:26 UTC, Ladirico commented
Hi @AliceAzzolini !
would you please check the English texts?
Thanks!

2023-10-17 12:51 UTC, AliceAzzolini approved these changes
I've edited the file myself and made a new commit, so it's all good to go now.

2023-10-18 07:10 UTC, shadowsheep1 requested changes

2023-10-18 07:10 UTC, shadowsheep1 commented on ts/navigation/params/AuthenticationParamsList.ts
> +  [ROUTES.AUTHENTICATION_OPT_IN]: ChoosedIdentifier;
```suggestion
  [ROUTES.AUTHENTICATION_OPT_IN]: ChoosenIdentifier;
```

2023-10-18 07:10 UTC, shadowsheep1 commented on ts/screens/authentication/NewOptInScreen.tsx
> +export type ChoosedIdentifier = {
```suggestion
export type ChoosenIdentifier = {
```

2023-10-18 07:10 UTC, shadowsheep1 commented on ts/navigation/params/AuthenticationParamsList.ts
> +import { ChoosedIdentifier } from "../../screens/authentication/NewOptInScreen";
```suggestion
import { ChoosenIdentifier } from "../../screens/authentication/NewOptInScreen";
```

2023-10-18 08:56 UTC, Ladirico commented on ts/navigation/params/AuthenticationParamsList.ts
> +  [ROUTES.AUTHENTICATION_OPT_IN]: ChoosedIdentifier;
done

2023-10-18 08:56 UTC, Ladirico commented on ts/navigation/params/AuthenticationParamsList.ts
> +import { ChoosedIdentifier } from "../../screens/authentication/NewOptInScreen";
done

2023-10-18 13:42 UTC, shadowsheep1 approved these changes
LGTM 👍

2023-10-19 09:35 UTC, merged