[SIW-468] Presentation optional claims selection
pagopa/io-app pull request #5138
Opened 2023-10-18 15:46 UTC by LazyAfternoons

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-10-20 13:54 UTC, hevelius requested changes

2023-10-20 13:54 UTC, hevelius commented on locales/en/index.yml
Where is The it locale?

2023-10-20 14:38 UTC, LazyAfternoons commented on locales/en/index.yml
For some reasons git didn't highlight the conflict on the it locale when I merged bundle/it-wallet. 
Fixed in 6d37870e, thank you.

2023-10-23 13:47 UTC, LazyAfternoons commented
> In the `ItwPresentationDataScreen` the claims selection section missed of "seleziona tutti" action as in figma. Is it ok?

That section in the FIGMA has an "IDEA" label, I implemented the "AS-IS" version.

2023-10-23 13:48 UTC, merged