[IOBP-492] BonusVacanze removal
pagopa/io-app pull request #5411
Opened 2024-01-18 14:53 UTC by forrest57

## Short description
Removed BonusVacanze

## List of changes proposed in this pull request
- removed screens and components
- removed logic where possible
- removed I18n keys (with the `remove_unused_locales` script, so some other unused keys were removed as well 😉 )

## How to test
1. open `dev-server`
2. `yarn generate`
3.  run the app
4. make sure that nothing breaks on launch
5. make sure that all vaguely "bonus-related" flows run correctly. this includes, but is not limited to:
- CGN
- wallet home
- new bonus onboarding
- new payment method onboarding
- possible old transaction history
6. run `yarn jest` to make sure it all runs smoothly.

2024-01-18 15:20 UTC, thisisjp commented
@forrest57 Are you sure about the `remove_unused_locales`?
I noticed some strings that shouldn't be removed, e.g.: `Puoi dirci com’è andata?` (it's part of the survey banner displayed when users successfully complete a payment)

2024-01-18 16:57 UTC, mastro993 requested changes

2024-01-18 16:57 UTC, mastro993 commented on locales/it/index.yml
> -          action: Vai al sondaggio
This must not be removed. This should be part of `WalletPaymentFeebackBanner`. Could you update it with proper keys?

2024-01-19 14:05 UTC, mastro993 approved these changes

2024-01-19 14:06 UTC, merged