[IOBP-535] Added german language for iOS app
pagopa/io-app pull request #5491
Opened 2024-02-06 08:45 UTC by mastro993

## Short description
This PR adds the german language for iOS app, visibile in the App Store.

## List of changes proposed in this pull request
- Added `de` locale to iOS project files

## How to test
German language should be listed in supported languages in the App Store app page.

2024-02-06 09:45 UTC, thisisjp commented on ios/ItaliaApp/de.lproj/Localizable.strings
> +"ALERT_DEVICE_ROOTED_TITLE" = "Device jailbroken";
@dhinterlechner could you please help us with the translation of these 2 strings? 🙏

2024-02-06 09:54 UTC, dhinterlechner commented on ios/ItaliaApp/de.lproj/Localizable.strings
> +"ALERT_DEVICE_ROOTED_TITLE" = "Device jailbroken";
Gerät mit Jailbreak

2024-02-06 09:55 UTC, dhinterlechner commented on ios/ItaliaApp/de.lproj/Localizable.strings
> +"ALERT_DEVICE_ROOTED_DESC" = "This device is jailbroken, you can't use this app for security reasons";
Dieses Gerät ist gejailbreakt, du kannst diese App aus Sicherheitsgründen nicht verwenden

2024-02-06 09:57 UTC, thisisjp requested changes

2024-02-06 09:57 UTC, thisisjp commented on ios/ItaliaApp/de.lproj/Localizable.strings
> +"ALERT_DEVICE_ROOTED_TITLE" = "Device jailbroken";
```suggestion
"ALERT_DEVICE_ROOTED_TITLE" = "Gerät mit Jailbreak";
```

2024-02-06 09:57 UTC, thisisjp commented on ios/ItaliaApp/de.lproj/Localizable.strings
> +"ALERT_DEVICE_ROOTED_DESC" = "This device is jailbroken, you can't use this app for security reasons";
```suggestion
"ALERT_DEVICE_ROOTED_DESC" = "Dieses Gerät ist gejailbreakt, du kannst diese App aus Sicherheitsgründen nicht verwenden";
```

2024-02-06 10:19 UTC, thisisjp approved these changes

2024-02-07 14:37 UTC, mastro993 commented
@dhinterlechner  we also need a translation for these strings. Do you mind translating them, please?

```strings
"NSCameraUsageDescription" = "Potrai leggere codici QR e pagare gli avvisi pagoPA.";
"NSCalendarsUsageDescription" = "Se acconsenti, potrai aggiungere le scadenze al tuo calendario e impostare un promemoria.";
"NSContactsUsageDescription" = "IO ha necessità di accedere ai tuoi contatti per permetterti di aggiungerli come partecipanti alle scadenze";
"NSFaceIDUsageDescription" = "IO ha necessità di accedere a Face ID per permetterti di effettuare un'autenticazione più veloce";
"NSPhotoLibraryUsageDescription" = "Potrai salvare bonus e certificati, caricare screenshot e avvisi di pagamento.";
"NSMicrophoneUsageDescription" = "IO ha necessità di accedere al microfono nel caso in cui desideri mandare una nota vocale";
"NSPhotoLibraryAddUsageDescription" = "Potrai salvare immagini dall'app sul tuo dispositivo.";
```

cc: @thisisjp

2024-02-08 09:26 UTC, dhinterlechner approved these changes
👍

2024-02-12 09:24 UTC, shadowsheep1 approved these changes
LGTM

2024-02-12 10:42 UTC, merged