[IOCOM-854] Add bottom sheet to display message contacts
pagopa/io-app pull request #5570
Opened 2024-03-05 11:04 UTC by adelloste

## Short description
This PR adds the bottom sheet to display message contacts.

<details open><summary>Details</summary>
<p>

| bs |
| - |
| <img src="https://github.com/pagopa/io-app/assets/29163287/0c0b4d07-3126-4f40-aa82-b6bc8b0323d0" width="300"/> |

</p>
</details> 

## List of changes proposed in this pull request
- added useMessageContactsBottomSheet hook to display the bottom sheet
- updated locales
- updated tests

## How to test
Using `io-dev-api-server`, generate a message. Activate experimental ds and open a message. Tap on _contacts_ action and check that the bottom sheet is displayed correctly.

2024-03-05 11:12 UTC, thisisjp requested changes

2024-03-05 11:12 UTC, thisisjp commented on locales/it/index.yml
> +    body: "Se non ti è chiaro il contenuto del messaggio, contatta l’ente che te lo ha inviato indicando l’ID del messaggio."
```suggestion
    body: "Se non ti è chiaro il contenuto del messaggio, contatta l’ente che te lo ha inviato."
```

2024-03-05 11:12 UTC, thisisjp commented on locales/en/index.yml
> +    body: "If something is unclear about the content of the message, contact the service directly by indicating the following message ID"
```suggestion
    body: "If you are unclear about the content of the message, contact the Institution that sent it to you."
```

2024-03-08 08:50 UTC, Vangaorth approved these changes
LGTM

2024-03-08 10:01 UTC, merged