[IOPID - 1509] Integrate new DS on email insert/validation in onboarding flow
pagopa/io-app pull request #5586
Opened 2024-03-12 13:38 UTC by Ladirico

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Integrate new DS
- Fix FAQ visualization
- Change flow
- Change copy
- Add mixpanel events (TODO)
- Refactor code 
   - Trasform validation modal into screen
   - Delete used screens (TODO)

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-03-12 15:13 UTC, francescopersico requested changes

2024-03-15 13:37 UTC, Ladirico commented on ts/screens/profile/EmailValidationScreen.tsx
> +      navigation.goBack();
thanks for the suggestion, it was not needed, navigation was already handled by the dispatch action

2024-03-15 13:37 UTC, Ladirico commented on ts/screens/profile/EmailValidationScreen.tsx
> +    timerElapsed?: () => void;
done! ✅

2024-03-15 13:38 UTC, Ladirico commented on ts/screens/profile/EmailValidationScreen.tsx
> +  const Countdown = (props: CountdownProps) => {
done, thanks for the suggestion! ✅

2024-03-15 13:39 UTC, Ladirico commented
@mariateresaventura please check the copy! 😁

2024-03-18 14:08 UTC, shadowsheep1 requested changes

2024-03-19 08:46 UTC, Ladirico commented on ts/store/sagas/emailValidationPollingSaga.ts
> +    yield* take(profileLoadSuccess);
Sorry, I don't understand the reason for this change, could you explain?

2024-03-19 08:48 UTC, Ladirico commented on ts/store/sagas/emailValidationPollingSaga.ts
> +  //   yield* put(emailValidationPollingStart());
I'm sorry, I don't understand, you are suggesting an as-is solution 😅

2024-03-19 09:37 UTC, Ladirico commented on ts/navigation/OnboardingNavigator.tsx
> -  const isEmailUniquenessValidationEnabled = useIOSelector(
done!

2024-03-19 09:37 UTC, Ladirico commented on ts/navigation/ProfileNavigator.tsx
> -  );
done!

2024-03-19 09:37 UTC, Ladirico commented on ts/navigation/ProfileNavigator.tsx
> +      component={CduEmailInsertScreen}
done!

2024-03-19 09:37 UTC, Ladirico commented on ts/navigation/OnboardingNavigator.tsx
> +      component={CduEmailInsertScreen}
done!

2024-03-19 09:38 UTC, Ladirico commented on ts/sagas/startup/checkAcknowledgedEmailSaga.ts
> +    // cduEmailScreen knows if the user comes from onboarding or not
done!

2024-03-19 09:38 UTC, Ladirico commented on ts/screens/profile/ProfileDataScreen.tsx
> +  // isEmailUniquenessValidationEnabled,
done!

2024-03-19 09:39 UTC, Ladirico commented on ts/screens/profile/__test__/ProfileDataScreen.test.tsx
> +  // });
I think I commented out those lines of code by mistake, I uncommented them!

2024-03-19 09:39 UTC, Ladirico commented on ts/screens/profile/__test__/ProfileDataScreen.test.tsx
> +  //   const { component } = renderComponent();
I think I commented out those lines of code by mistake, I uncommented them!

2024-03-19 10:29 UTC, Ladirico commented on ts/screens/profile/EmailValidationSendEmailScreen.tsx
> +  );
done! Thanks for the suggestion!

2024-03-19 10:33 UTC, shadowsheep1 commented on ts/store/sagas/emailValidationPollingSaga.ts
> +  //   yield* put(emailValidationPollingStart());
I suggest to remove the comment ;)

2024-03-19 10:33 UTC, Ladirico commented on ts/screens/profile/EmailValidationSendEmailScreen.tsx
> +        "ONBOARDING_READ_EMAIL_SCREEN" | "PROFILE_EMAIL_INSERT_SCREEN",
done!

2024-03-19 10:36 UTC, shadowsheep1 commented on ts/store/sagas/emailValidationPollingSaga.ts
> +    yield* take(profileLoadSuccess);
Yep! You are dispatching `profileLoadRequest()`, this trigger an API call that reload the citizen profile. Before checking the validity of the email, you should wait for the API call to end: the take of `profileLoadSuccess` (API call succesfully ended) should be before checking the validity of the email. What do you think?

2024-03-19 10:38 UTC, Ladirico commented on ts/store/sagas/emailValidationPollingSaga.ts
> +  //   yield* put(emailValidationPollingStart());
done!

2024-03-19 10:44 UTC, Ladirico commented on ts/store/sagas/emailValidationPollingSaga.ts
> +    yield* take(profileLoadSuccess);
oh yes! thanks!

2024-03-19 10:47 UTC, Ladirico commented on ts/store/sagas/emailValidationPollingSaga.ts
> +    yield* take(profileLoadSuccess);
done!

2024-03-19 15:22 UTC, shadowsheep1 reviewed
I've found a critical path:
- User already logged in.
- User with invalid email.
- User go straight ahead to email validation.
- After a successful validation is stuck in a wrong navigation stack.

Are you able to reproduce it or am I missing something?

<details><summary>Details</summary>
<p>

| Wrong Way ❌ |
| - | 
| <video src="https://github.com/pagopa/io-app/assets/16268789/c8487f28-b3cc-4bae-92e8-76febedb02e6" /> |

</p>
</details>

2024-03-26 15:02 UTC, shadowsheep1 commented
We close it due to a wrong rebase.

2024-03-26 15:02 UTC, closed without merging