[IOPLT-394] Bump Xcode version used to build the app
pagopa/io-app pull request #5611
Opened 2024-03-20 15:31 UTC by CrisTofani

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-03-25 09:22 UTC, shadowsheep1 commented on ios/fastlane/Fastfile
> +    # # upload to App store
Double comment ;)

2024-03-25 09:22 UTC, shadowsheep1 commented on ios/fastlane/Fastfile
> +    # # upload to App store
```suggestion
    # upload to App store
```

2024-03-26 12:14 UTC, LazyAfternoons approved these changes
LGTM

2024-03-26 12:28 UTC, shadowsheep1 requested changes
The best way to test this, is to put this workflow in a personal repo and with tamte luring inside the runner to see if all the commands run smoothly. What do you think?

2024-03-26 12:31 UTC, CrisTofani commented
> The best way to test this, is to put this workflow in a personal repo and with tamte lurking inside the runner to see if all the commands run smoothly. What do you think?

@shadowsheep1 I ran an execution of the build process here https://github.com/pagopa/io-app/actions/runs/8362091374?pr=5611 just commenting the upload to app store job in the fastfile to avoid the rejection by TF

2024-03-26 12:32 UTC, shadowsheep1 approved these changes
LGTM

2024-03-26 13:10 UTC, merged