feat: [IOBP-636,IOBP-646] Add legacy transactions lists
pagopa/io-app pull request #5796
Opened 2024-05-24 13:37 UTC by Hantex9

## ⚠️ This PR depends on #5768 ⚠️

## Short description
This PR implements the ability to view “legacy” transactions that are not available through biz-events at the moment. 

## List of changes proposed in this pull request
- Added a legacy list screen that retrieves the old transactions not available with biz-events;
- Connected the legacy list screen with the previous transaction details that shows transaction info with a reduced amount of data;
- Added a CTA to access to this new page from:
   - `PaymentsHomeEmptyScreenContent`
   - Into the biz-events transaction list when the user reaches the end of the list.

## How to test
- Checkout the dev-server with the following PR: https://github.com/pagopa/io-dev-api-server/pull/369
- Open the new payment landing page and try to reach the CTA from the entry point listed above, you should be able to see the previous transactions with less data shown.

## Preview

WIP

2024-06-11 10:10 UTC, mastro993 requested changes

2024-06-11 10:10 UTC, mastro993 commented on ts/features/payments/transaction/components/PaymentsLegacyAttachmentBottomSheet.tsx
> +};
We could simplify this hook as follows.
The `useIOBottomSheet` hook internally uses the `H4` typography component to render the title.
And we can return directly the composed hook, avoiding to use of the spread operator.
What do you think?

```suggestion
/**
 * This custom hook, usePaymentsLegacyAttachmentBottomSheet, is designed to display a bottom sheet
 * containing detailed information about where the user can find the legacy transaction recepit.
 */
const usePaymentsLegacyAttachmentBottomSheet = (): IOBottomSheetModal =>
  useIOBottomSheetAutoresizableModal({
    title: I18n.t("features.payments.transactions.legacy.bottomSheet.title"),
    component: (
      <View>
        <ParagraphWithTitle
          title={I18n.t(
            "features.payments.transactions.legacy.bottomSheet.noticeHeading"
          )}
          body={I18n.t(
            "features.payments.transactions.legacy.bottomSheet.noticeBody"
          )}
        />
        <VSpacer size={24} />
        <ParagraphWithTitle
          title={I18n.t(
            "features.payments.transactions.legacy.bottomSheet.allNoticesHeading"
          )}
          body={I18n.t(
            "features.payments.transactions.legacy.bottomSheet.allNoticesBody"
          )}
        />
        <VSpacer size={48} />
      </View>
    )
  });
```

2024-06-11 13:47 UTC, thisisjp requested changes
you forgot a word from the Figma file ;)

2024-06-11 13:47 UTC, thisisjp commented on locales/en/index.yml
> +          allNoticesHeading: Tutti gli avvisi
```suggestion
          allNoticesHeading: Tutti gli altri avvisi
```

2024-06-11 13:47 UTC, thisisjp commented on locales/it/index.yml
> +          allNoticesHeading: Tutti gli avvisi
```suggestion
          allNoticesHeading: Tutti gli altri avvisi
```

2024-06-12 10:04 UTC, thisisjp approved these changes

2024-06-12 10:04 UTC, merged