[IOAPPX-339] Replace `ButtonExtendedOutline` with `ModuleSummaryItem`
pagopa/io-app pull request #5946
Opened 2024-07-09 13:26 UTC by dmnplb

> [!warning]
> This PR depends on:
> * https://github.com/pagopa/io-app-design-system/pull/305

## Short description
This PR replaces the `ButtonExtendedOutline` with `ModuleSummaryItem`.

## List of changes proposed in this pull request
- Replace `ButtonExtendedOutline` component in the IDPay flow
- Update relative documentation in the **Modules** screen (Design System)

## How to test
1. Launch the app in the local environment
2. Go to the **Design System → Modules** screen

2024-07-11 10:08 UTC, CrisTofani requested changes
I may have missed some Alert component, generally speaking I guess we can restore the refs as a component ref instead of viewRef prop now removed

2024-07-11 10:08 UTC, CrisTofani commented on ts/screens/onboarding/OnboardingTosScreen.tsx
> -            viewRef={viewRef}
what about restoring it as `ref`?

2024-07-11 10:08 UTC, CrisTofani commented on ts/features/wallet/component/features/PaymentMethodFeatures.tsx
> +      <Alert variant="error" content={I18n.t("wallet.methodDetails.expired")} />
what about restoring the ref?

2024-07-11 10:08 UTC, CrisTofani commented on ts/screens/authentication/TestAuthenticationScreen.tsx
> +    <Alert variant="error" title={title} content={content} />
ditto

2024-07-11 10:08 UTC, CrisTofani commented on ts/screens/authentication/TestAuthenticationScreen.tsx
> -      <Alert viewRef={viewRef} variant="success" content={"Success"} />
ditto

2024-07-11 11:44 UTC, dmnplb commented
> I may have missed some Alert component, generally speaking I guess we can restore the refs as a component ref instead of viewRef prop now removed

@CrisTofani In most parts of the codebase, the `viewRef` prop was added because it was required by the original component API. Unless it's added voluntarily, I think it's better to get rid of it.

2024-07-16 07:31 UTC, CrisTofani approved these changes

2024-07-16 07:37 UTC, merged