[IOPLT-603] Sets Android API Level 34
pagopa/io-app pull request #5947
Opened 2024-07-09 15:15 UTC by CrisTofani

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-07-18 11:07 UTC, Vangaorth requested changes

2024-07-18 11:07 UTC, Vangaorth commented on android/build.gradle
>          buildToolsVersion = "33.0.2"
Should be also switch to `buildTollsVersion` to `34.0.0`?

2024-07-18 13:36 UTC, Vangaorth approved these changes
Build tools updated to 34.0.0
react-native-share to latest version (in order to support share on Android 14)

Tested on each message flow and also the sharing of the payment receipt.

LGTM

2024-07-22 11:10 UTC, shadowsheep1 approved these changes
LGTM: Tested 
- Build
- EIC Login
- Camera Permissions on both Android 14 and 12.

We need just to remember that for the future:

```shell
[VisionCamera] react-native-worklets-core not found, Frame Processors disabled!
WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (7.4.2) was tested up to compileSdk = 33

This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 34
```

2024-07-22 22:09 UTC, LazyAfternoons approved these changes
LGTM, tested the QR code scan on the following devices without noticing any regression: 
- iPhone XS@17;
- Samsung S23@14;
- Pixel 4a@13;
- Honor 9@9;
- Samsung A51@13.

2024-07-23 07:50 UTC, merged