[IOPID-2016,IOPID-2017] wip: first implementation
pagopa/io-app pull request #5963
Opened 2024-07-12 10:17 UTC by shadowsheep1

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-07-19 15:19 UTC, Ladirico requested changes

2024-07-19 15:19 UTC, Ladirico commented on ts/sagas/startup.ts
> +  starupAction?: ActionType<typeof startApplicationInitialization>
i think it's a typo 
```suggestion
  startupAction?: ActionType<typeof startApplicationInitialization>
```

2024-07-19 15:19 UTC, Ladirico commented on ts/sagas/startup.ts
> +    starupAction?.payload && starupAction.payload.handleSessionExpiration
as above
```suggestion
    startupAction?.payload && starupAction.payload.handleSessionExpiration
```

2024-07-19 15:19 UTC, Ladirico commented on ts/sagas/startup.ts
> +    starupAction?.payload?.showIdentificationModalAtStartup ?? true;
as above 
```suggestion
    startupAction?.payload?.showIdentificationModalAtStartup ?? true;
```

2024-07-23 06:08 UTC, ChrisMattew approved these changes

2024-07-23 06:56 UTC, Ladirico approved these changes
LGTM!

2024-07-23 07:32 UTC, merged