chore: align default `tosVersion` to the remote one
pagopa/io-app pull request #5978
Opened 2024-07-16 16:07 UTC by shadowsheep1

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-07-18 13:48 UTC, ChrisMattew approved these changes

2024-07-19 15:46 UTC, Ladirico requested changes

2024-07-19 15:46 UTC, Ladirico commented on ts/screens/profile/components/__test__/ShareDataComponent.test.tsx
> +    "FAKE_ROUTE",
You can use "DUMMY" as the other component without route in the app 

```suggestion
    "DUMMY",
```

2024-07-22 11:06 UTC, Ladirico approved these changes
LGTM!

2024-07-22 11:58 UTC, merged