[IOAPPX-357] Upgrades bottom-sheets library
pagopa/io-app pull request #6062
Opened 2024-07-29 13:48 UTC by CrisTofani

## Short description
This PR aims to upgrade bottom-sheet library to solve rendering glitches

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-07-30 07:44 UTC, dmnplb commented
The problem we discussed yesterday does not seem to be related to the package version. By the way, I noticed that the visual issue seems to be related to the `Autoresizable...' ones, because the static ones work fine.

2024-08-06 08:17 UTC, dmnplb commented
I've just updated the `jest` snapshots (https://github.com/pagopa/io-app/pull/6062/commits/6b63e183aced26a44e07b578987b89c7c2b2af6a) but I noticed that some snapshots no longer contain **a11y** related attributes. Before merging this PR, we should make sure that we don't have any accessibility regressions.

2025-02-24 09:08 UTC, LeleDallas commented on ts/utils/hooks/bottomSheet.tsx
> +      enableDynamicSizing={snapPoint ? false : true}
Consider updating the `enableDynamicSizing` prop to use `!snapPoint` instead of `snapPoint ? false : true`

```suggestion
      enableDynamicSizing={!snapPoint}
```

2025-02-24 09:08 UTC, LeleDallas commented on ts/utils/hooks/bottomSheet.tsx
> +  footer?: React.ReactElement;
Consider simplifying the type definitions by importing the necessary types directly from react

```suggestion
  component:ReactNode;
  title: string |ReactNode;
  snapPoint?: NonEmptyArray<number | string>;
  footer?: ReactElement;
```

2025-02-24 16:35 UTC, LeleDallas approved these changes
B&P stream looks good!💫

2025-02-25 10:29 UTC, Vangaorth requested changes
The accessibility does not work properly on `iOS`, since the focus is not on the bottom sheet content but on the bottom sheet's backdrop. Later is on the bottom sheet itself and only after that it moves to the content.

2025-03-18 10:25 UTC, LeleDallas commented
@Vangaorth  @CrisTofani I found out that setting the `accessible` flag to `false` for all `gorhom/bottom-sheet` component in `useIOBottomSheetModal` was enough to resolve partially the problem of the screen reader making two separate `bottom sheet` announcements. The remaining issue seems to be related to `BottomSheetScrollView`

2025-04-22 14:58 UTC, Vangaorth commented
@CrisTofani @LeleDallas I made a patch to the bottom-sheet package that:
- removes accessibility from the background
- gives accessibility focus to the bottom-sheet content.

On iOS, VoiceOver announces the bottom-sheet and the user can swipe to the inner content. On Android, focus is directed on the inner content but I think that it is due to the always-fullscreen mode.

Let me know, if this works for you, for me the PR can be merged

2025-04-22 15:13 UTC, LeleDallas commented
> @CrisTofani @LeleDallas I made a patch in [1ad2fcf](https://github.com/pagopa/io-app/commit/1ad2fcf47367cade3b964d6588888acaf36dd8e6) to the bottom-sheet package that:
> 
> * removes accessibility from the background
> * gives accessibility focus to the bottom-sheet content.
> 
> On iOS, VoiceOver announces the bottom-sheet and the user can swipe to the inner content. On Android, focus is directed on the inner content but I think that it is due to the always-fullscreen mode.
> 
> Let me know, if this works for you, for me the PR can be merged

For me it's ✅

2025-04-23 09:52 UTC, mastro993 commented
I noticed a change in the footer component's animation between the library versions. In the new version, the slide-from-bottom animation for the footer is no longer present or less visible. You can see the difference in the video below.

| `4.1.5` | `5.1.2` |
| --- | --- |
|  <video src="https://github.com/user-attachments/assets/9bb578b8-8460-4573-bd59-7f09577594be" /> |  <video src="https://github.com/user-attachments/assets/ce268d8c-3f84-4d13-a986-6e036b0c1f56" /> |

I was able to do a quick fix by moving the CTA from the footer to the content's component here: https://github.com/pagopa/io-app/pull/6062/commits/bebae0d264c2b89acb5f985bcba1e09c50d50b07

I think we should address this behaviour in an separated issue/PR.

2025-04-23 09:54 UTC, mastro993 approved these changes
Aside from the minor issue mentioned above, the PR looks good. All modals within the IT Wallet flows work flawlessly, so LGTM!

2025-04-23 13:05 UTC, merged