[IOPID-2322] - CieID Error handling
pagopa/io-app pull request #6306
Opened 2024-10-18 08:47 UTC by ChrisMattew

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-10-22 12:40 UTC, ChrisMattew commented
@mariateresaventura copy review needed 🙏🏻

2024-10-25 10:52 UTC, Ladirico requested changes

2024-10-25 12:45 UTC, ChrisMattew commented on ts/screens/authentication/components/AuthErrorComponent.tsx
> +export const IOS_OPERATION_CANCELED_MESSAGE =
I agree!

2024-10-25 12:45 UTC, ChrisMattew commented on ts/features/cieLogin/components/CieIdLoginWebView.tsx
> +      // TODO: Check missing SAML response (error message)
Good catch, thanks!

2024-10-25 15:35 UTC, mariateresaventura commented
> @mariateresaventura copy review needed 🙏🏻

Done!

2024-10-28 11:58 UTC, Ladirico approved these changes
LGTM!

2024-10-28 11:59 UTC, merged