chore: [IOAPPX-405] Removing unused react imports
pagopa/io-app pull request #6562
Opened 2024-12-17 17:41 UTC by LeleDallas

## Short description
This pull request updates the ESLint and Babel configurations, along with package dependencies, to support the latest version of the JSX transform. This new transform enable the use of JSX without importing React.

## List of changes proposed in this pull request
- Apply changes as described in official documentation [here](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) 

## How to test
Ensure that the application works as expected, without any compilation errors or runtime crashes

2024-12-18 15:00 UTC, Vangaorth requested changes
I think that we can also remove all the 
`import * as React from "react"`
in favour of specifics imports. What do you think?

2024-12-19 08:46 UTC, LeleDallas commented
> I think that we can also remove all the `import * as React from "react"` in favour of specifics imports. What do you think?

Addressed here 1e78ae8047c743d643e2f79b1743c5311346ec9b

The only file that still have the should be `svg.d.ts` as documented [here](https://github.com/kristerkari/react-native-svg-transformer?tab=readme-ov-file#using-typescript)

2024-12-19 10:17 UTC, Vangaorth approved these changes
LGTM! Tested on both iOS and Android

2025-01-16 13:33 UTC, mastro993 approved these changes
LGTM 🚀

2025-01-16 15:05 UTC, CrisTofani approved these changes
LGTM

2025-01-17 16:45 UTC, merged