[SIW-1455] eID re-issuing when jwt is expiring or expired
pagopa/io-app pull request #6580
Opened 2024-12-24 09:54 UTC by RiccardoMolinari95

## Short description
This PR handle the reissuing of eID, when the jwt is expired or expiring.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2025-01-07 16:36 UTC, mastro993 commented on ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
> +        <ItwEidLifecycleAlert navigation={navigation} />
Can we use the `useIONavigation` hook inside the component instead?

2025-01-07 16:43 UTC, mastro993 commented on ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
> +  | undefined;
```suggestion
export type ItwIdentificationModeSelectionScreenNavigationParams = {
      eidReissuing?: boolean;
    };
    
export type ScreenProps = IOStackNavigationRouteProps<
  ItwParamsList,
  "ITW_IDENTIFICATION_MODE_SELECTION"
>

```

I believe this approach is more appropriate because:
- the optional `eidReissuing` parameter is not hidden. This makes it clear to anyone using this screen that the parameter exists and is optional
- by defining a dedicated type for the screen props we are improving readability and maintainability

What do you think?

2025-01-07 16:57 UTC, RiccardoMolinari95 commented on ts/features/itwallet/common/components/ItwEidInfoBottomSheetContent.tsx
> +        <ItwEidLifecycleAlert navigation={navigation} />
I had some problems using `useIONavigation` inside the `ItwEidLifecycleAlert` component, so I preferred to pass it from the parent component to `ItwEidLifecycleAlert` as a prop since it was already available.
Let me know if this is okay for you, or if you would like me to try integrating it directly into `ItwEidLifecycleAlert`

2025-01-08 08:39 UTC, RiccardoMolinari95 commented on ts/features/itwallet/identification/screens/ItwIdentificationModeSelectionScreen.tsx
> +  | undefined;
Yes, you're right! Please check here [2ca518f](https://github.com/pagopa/io-app/pull/6580/commits/2ca518f4bc988398916844ffb98a03c95fb143cf) ( `console.log` deleted here [b72bffd](https://github.com/pagopa/io-app/pull/6580/commits/b72bffd9e31c9bdfe8474870a14ce648a7cf2595))

2025-01-13 13:06 UTC, gispada commented on ts/features/itwallet/machine/eid/machine.ts
> +            actions: [
We are duplicating this part. Can we extract only the `target` action? Would something like the following work?

```js
[
  {
    actions: [
      assign(({ event }) => ({
        walletInstanceAttestation: event.output
      })),
      { type: "storeWalletInstanceAttestation" }
    ]
  },
  {
    guard: "isReissuing",
    target: "UserIdentification"
  },
  {
    target: "IpzsPrivacyAcceptance"
  }
]
```

2025-01-13 13:06 UTC, gispada commented on ts/features/itwallet/machine/eid/machine.ts
> +                guard: "isReissuing",
We are duplicating here as well. Can this part be improved?

2025-01-13 17:01 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/eid/machine.ts
> +    CheckingWalletInstanceAttestation: {
Yes, you're right it's not necessary `CheckingWalletInstanceAttestation`.  Addressed in [0fb11ee](https://github.com/pagopa/io-app/pull/6580/commits/0fb11ee57c264ed94af7c258ef3edffedfe0a019)

2025-01-13 17:01 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/eid/machine.ts
> +                guard: "isReissuing",
Addressed in [0fb11ee](https://github.com/pagopa/io-app/pull/6580/commits/0fb11ee57c264ed94af7c258ef3edffedfe0a019)

2025-01-13 17:06 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/eid/machine.ts
> +            actions: [
I preferred to repeat the function twice because I had issues simplifying it. Unfortunately, in `onDone` I don't think it's possible to insert an array of `target`, and the only way would be to use a single `action` with a single `target`, which would require creating a new `state`. Therefore, I chose to repeat the `action` twice rather than creating a new `state`.

2025-01-14 09:34 UTC, gispada commented on ts/features/itwallet/machine/eid/machine.ts
> +          entry: [
I don't think it's correct to store the credential and set the WI to valid on entry, when simply displaying the preview. The user might decide to cancel the activation and that should not activate the wallet.

If there is no way to avoid the repetition of actions, let's keep them duplicated.

2025-01-14 09:35 UTC, gispada commented on ts/features/itwallet/machine/eid/machine.ts
> +            actions: [
I see. Thanks for the clarification.

2025-01-14 10:50 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/eid/machine.ts
> +          entry: [
Thanks for the point. Yes i restored the previous situation in [5ebd8ae](https://github.com/pagopa/io-app/pull/6580/commits/5ebd8ae76279120c5ef426ecde5c70416ad2f038)

2025-01-15 08:13 UTC, gispada commented on ts/features/itwallet/machine/eid/machine.ts
> +            guard: "isReissuingAndSessionExpired",
We can use the `and` higher guard: `and(["isReissuing", "isSessionExpired"])`.

I have a question on this error case: is it correct to close the issuance (action that pops the navigation stack) and return to idle while the user re-authenticates? Are we sure the user can resume the issuance flow without getting stuck in an "impossible" state? Just to be sure.

2025-01-17 08:51 UTC, mastro993 commented on ts/features/itwallet/onboarding/screens/WalletCardOnboardingScreen.tsx
> +      }
We can move this logic inside the machine. What do you think?

2025-01-17 09:03 UTC, mastro993 commented on ts/features/itwallet/presentation/screens/ItwPresentationEidVerificationExpiredScreen.tsx
> +  });
No need to use the hook. We can remove the header in the screen options within the `ItwStackNavigator` component. What do you think?

2025-01-17 09:06 UTC, mastro993 commented on ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
> +  navigation
```suggestion
```
Consider using the `useNavigation` hook directly within the component instead of passing it as a prop.

2025-01-17 09:08 UTC, mastro993 requested changes
Everything works as expected, but we need to do some adjustments before merging the PR

2025-01-17 12:38 UTC, RiccardoMolinari95 commented on ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
> +  navigation
Yes, you're right, but since `ItwEidInfoBottomSheetContent` is not inside any `NavigationContainer`, it's not possible to use the `useIONavigation` hook within the component.
As you can see, even for `ItwEidInfoBottomSheetContent`, `navigation` was passed as a prop, and the same needs to be done for `ItwEidLifecycleAlert` within `ItwEidInfoBottomSheetContent`.
The alternative would be to add `ItwEidInfoBottomSheetContent` inside a navigator as a screen. Is it worth it?
Are there any other solutions that I might not be aware of?

2025-01-17 14:01 UTC, mastro993 commented on ts/features/itwallet/common/components/ItwEidLifecycleAlert.tsx
> +  navigation
In this, case we are forced to pass down the navigation props as you did.
[Reading the documentation](https://reactnavigation.org/docs/navigating-without-navigation-prop/), we should not use the ref to call the navigation service.

2025-01-17 14:55 UTC, mastro993 commented on ts/features/itwallet/machine/credential/guards.ts
> +      isSelectCredentialEvent(event) && event.skipNavigation === true,
Could be simplified: 
```suggestion
      event.type === "select-credential" && event.skipNavigation === true,
```

2025-01-20 15:44 UTC, mastro993 requested changes

2025-01-20 15:44 UTC, mastro993 commented on ts/features/itwallet/machine/credential/guards.ts
> +  const store = useIOStore();
You can't use hooks outside of components or other hooks, you need to pass the `store` as an argument.
```suggestion
export const createCredentialIssuanceGuardsImplementation = (store: ReturnType<typeof useIOStore>) => {
```

2025-01-20 15:56 UTC, mastro993 commented on ts/features/itwallet/machine/eid/machine.ts
> +    }))
The spread operator is unnecessary in the `assign` actions
```suggestion
    setIsReissuing: assign(() => ({
      isReissuing: true
    }))
```

2025-01-20 16:01 UTC, mastro993 commented on ts/features/itwallet/presentation/screens/ItwPresentationEidVerificationExpiredScreen.tsx
> +  const bodyPropsArray: Array<BodyProps> = useMemo(
This `useMemo` is unnecessary, imho. It does not contain any expensive calculation, it does not depend on anything and the parent component does not seem to have any re-rendering. 
I think we can safely remove it. What do you think?

2025-01-20 16:09 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/credential/guards.ts
> +  const store = useIOStore();
Yes, you're right! Addressed in [0828a30](https://github.com/pagopa/io-app/pull/6580/commits/0828a300826f23e9906e466a5ed4ec313f523397)

2025-01-20 16:37 UTC, mastro993 commented on ts/features/itwallet/machine/credential/machine.ts
> +    isWalletValid: notImplemented,
Does this guard also check for the eID jwt expiration? Because if I mock the eID status to `jwtExpired` this guard returns `true`.
In fact, it calls `itwLifecycleIsValidSelector`, which does not take in consideration the eID expiration and, in my opinion, it is not the correct behavior.

2025-01-22 17:18 UTC, mastro993 commented on ts/features/itwallet/machine/credential/guards.ts
> +    );
We have a selector to get directly the eID status

```suggestion
    const eidStatus = itwCredentialsEidStatusSelector(store.getState());
    return eidStatus === "jwtExpired"
```

2025-01-22 17:20 UTC, mastro993 commented on ts/features/itwallet/machine/credential/machine.ts
> +            guard: and(["isEidExpired", "isSkipNavigation"]),
Do we need to check if `isSkipNavigation` is true? If the eID is expired we need to navigate to a screen in any case.

2025-01-22 17:42 UTC, RiccardoMolinari95 commented on ts/features/itwallet/machine/credential/machine.ts
> +            guard: and(["isEidExpired", "isSkipNavigation"]),
Yes, you're right we don't need it

2025-01-23 14:36 UTC, mastro993 approved these changes
LGTM

2025-01-24 08:59 UTC, merged